import { createResendEmailProvider } from "./email-provider.server";
import { createTelnyxSmsProvider } from "./sms-provider.server";

export type NotificationEnvironment = { RESEND_API_KEY?: string; RESEND_FROM_EMAIL?: string; TELNYX_API_KEY?: string; TELNYX_FROM_NUMBER?: string; TELNYX_WEBHOOK_PUBLIC_KEY?: string; APP_BASE_URL?: string };
type Preferences = { appointmentEmailEnabled: number; appointmentSmsEnabled: number; smsOptedOutAt: string | null; emailEnabled: string; smsEnabled: string };
type Appointment = { id: number; userId: number; name: string; email: string; phone: string | null; date: string; time: string | null; loadType: string; eventName: string | null };

export type NotificationProviderStatus = { provider: "resend" | "telnyx"; status: "Configured" | "Missing API Key" | "Missing Sender Address" | "Missing Sender Number" | "Missing Required Provider Configuration"; configured: boolean; senderName?: string; senderAddress?: string; replyTo?: string; senderNumber?: string; messagingProfileId?: string; inboundWebhook: { endpoint: string; signatureValidationConfigured: boolean } };
const settingsDefaults = { "notifications.first_reminder_enabled": "1", "notifications.first_reminder_offset_minutes": "10080", "notifications.second_reminder_enabled": "1", "notifications.second_reminder_offset_minutes": "1440", "notifications.email_enabled": "1", "notifications.sms_enabled": "1", "notifications.email_provider": "resend", "notifications.email_sender_name": "Trice Auctions", "notifications.email_sender_address": "", "notifications.email_reply_to": "", "notifications.sms_provider": "telnyx", "notifications.sms_sender_number": "", "notifications.sms_messaging_profile_id": "" };
export async function getNotificationSettings(db: D1Database) { const { results } = await db.prepare("SELECT key, value FROM settings WHERE key LIKE 'notifications.%'").all<{key:string;value:string}>(); return { ...settingsDefaults, ...Object.fromEntries(results.map(x => [x.key, x.value])) }; }
export async function saveNotificationSettings(db: D1Database, values: Record<string, string>) { await db.batch(Object.entries(values).map(([key,value]) => db.prepare("INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(key,value))); }
export function getNotificationProviderStatuses(settings: Record<string, string>, env: NotificationEnvironment): { email: NotificationProviderStatus; sms: NotificationProviderStatus } {
  const emailProvider = settings["notifications.email_provider"] === "resend" ? "resend" : "resend";
  const smsProvider = settings["notifications.sms_provider"] === "telnyx" ? "telnyx" : "telnyx";
  const senderAddress = settings["notifications.email_sender_address"].trim() || env.RESEND_FROM_EMAIL?.trim() || "";
  const senderNumber = settings["notifications.sms_sender_number"].trim() || env.TELNYX_FROM_NUMBER?.trim() || "";
  const emailStatus = !env.RESEND_API_KEY ? "Missing API Key" : !senderAddress ? "Missing Sender Address" : "Configured";
  const smsStatus = !env.TELNYX_API_KEY ? "Missing API Key" : !senderNumber ? "Missing Sender Number" : "Configured";
  return { email: { provider: emailProvider, status: emailStatus, configured: emailStatus === "Configured", senderName: settings["notifications.email_sender_name"], senderAddress, replyTo: settings["notifications.email_reply_to"], inboundWebhook: { endpoint: "", signatureValidationConfigured: false } }, sms: { provider: smsProvider, status: smsStatus, configured: smsStatus === "Configured", senderNumber, messagingProfileId: settings["notifications.sms_messaging_profile_id"], inboundWebhook: { endpoint: "/webhooks/telnyx/sms", signatureValidationConfigured: Boolean(env.TELNYX_WEBHOOK_PUBLIC_KEY) } } };
}
export async function sendTestNotification(db: D1Database, env: NotificationEnvironment, input: { channel: "email" | "sms"; destination: string; subject?: string }) {
  const settings = await getNotificationSettings(db);
  const providers = getNotificationProviderStatuses(settings, env);
  if (input.channel === "email") {
    if (!providers.email.configured) throw new Error(`Email testing unavailable: ${providers.email.status}.`);
    return createResendEmailProvider({ apiKey: env.RESEND_API_KEY, from: formatSender(providers.email.senderName || "", providers.email.senderAddress || "") }).send({ to: input.destination, subject: input.subject || "Trice Auctions Notification Test", text: "This is a test email from the Trice Auctions notification system.", replyTo: providers.email.replyTo || undefined });
  }
  if (!providers.sms.configured) throw new Error(`SMS testing unavailable: ${providers.sms.status}.`);
  return createTelnyxSmsProvider({ apiKey: env.TELNYX_API_KEY, from: providers.sms.senderNumber }).send({ to: input.destination, text: "Trice Auctions test message. Your SMS notification configuration is working." });
}
export async function getNotificationPreferences(db: D1Database, userId: number) { await db.prepare("INSERT INTO user_notification_preferences(user_id) VALUES (?) ON CONFLICT(user_id) DO NOTHING").bind(userId).run(); return db.prepare("SELECT appointment_email_enabled AS appointmentEmailEnabled, appointment_sms_enabled AS appointmentSmsEnabled, sms_consent_at AS smsConsentAt, sms_consent_source AS smsConsentSource, sms_opted_out_at AS smsOptedOutAt FROM user_notification_preferences WHERE user_id=?").bind(userId).first<{appointmentEmailEnabled:number;appointmentSmsEnabled:number;smsConsentAt:string|null;smsConsentSource:string|null;smsOptedOutAt:string|null}>(); }
export async function updateNotificationPreferences(db:D1Database,userId:number,input:{emailEnabled:boolean;smsEnabled:boolean;source:string;hasValidPhone:boolean}) { if (input.smsEnabled && !input.hasValidPhone) return {ok:false as const,error:"Add a valid phone number before enabling SMS notifications."}; await db.prepare(`INSERT INTO user_notification_preferences(user_id,appointment_email_enabled,appointment_sms_enabled,sms_consent_at,sms_consent_source,sms_opted_out_at,updated_at) VALUES (?,?,?,?,?,CASE WHEN ? THEN NULL ELSE NULL END,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET appointment_email_enabled=excluded.appointment_email_enabled, appointment_sms_enabled=excluded.appointment_sms_enabled, sms_consent_at=CASE WHEN excluded.appointment_sms_enabled=1 AND user_notification_preferences.appointment_sms_enabled=0 THEN CURRENT_TIMESTAMP ELSE user_notification_preferences.sms_consent_at END, sms_consent_source=CASE WHEN excluded.appointment_sms_enabled=1 THEN excluded.sms_consent_source ELSE user_notification_preferences.sms_consent_source END, sms_opted_out_at=CASE WHEN excluded.appointment_sms_enabled=1 THEN NULL ELSE user_notification_preferences.sms_opted_out_at END,updated_at=CURRENT_TIMESTAMP`).bind(userId,input.emailEnabled?1:0,input.smsEnabled?1:0,input.smsEnabled?new Date().toISOString():null,input.source,input.smsEnabled?1:0,input.smsEnabled?1:0).run(); return {ok:true as const}; }

export async function queueAppointmentNotifications(db:D1Database, appointmentId:number, kind:"confirmation"|"rescheduled"|"cancelled"|"reminder_1"|"reminder_2", scheduledAt = new Date().toISOString()) { const appointment=await loadAppointment(db,appointmentId); if(!appointment) return; const settings=await getNotificationSettings(db); const prefs=await preferences(db,appointment.userId,settings); const base=appointmentLink(appointment,kind); if(settings["notifications.email_enabled"]==="1"&&prefs.appointmentEmailEnabled) await insertJob(db,{userId:appointment.userId,appointmentId,kind,channel:"email",recipient:appointment.email,scheduledAt,payload:base}); if(settings["notifications.sms_enabled"]==="1"&&prefs.appointmentSmsEnabled&&!prefs.smsOptedOutAt&&validPhone(appointment.phone)) await insertJob(db,{userId:appointment.userId,appointmentId,kind,channel:"sms",recipient:appointment.phone!,scheduledAt,payload:base}); }
export async function queueAppointmentCreated(db:D1Database,appointmentId:number) { await queueAppointmentNotifications(db,appointmentId,"confirmation"); await scheduleReminders(db,appointmentId); }
export async function queueAppointmentRescheduled(db:D1Database,appointmentId:number) { await cancelFutureAppointmentReminders(db,appointmentId); await queueAppointmentNotifications(db,appointmentId,"rescheduled"); await scheduleReminders(db,appointmentId); }
export async function queueAppointmentCancelled(db:D1Database,appointmentId:number) { await cancelFutureAppointmentReminders(db,appointmentId); await queueAppointmentNotifications(db,appointmentId,"cancelled"); }
export async function cancelFutureAppointmentReminders(db:D1Database,appointmentId:number) { await db.prepare("UPDATE notification_jobs SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE appointment_id=? AND notification_type IN ('reminder_1','reminder_2') AND status IN ('pending','processing')").bind(appointmentId).run(); }
async function scheduleReminders(db:D1Database,appointmentId:number) { const a=await loadAppointment(db,appointmentId); if(!a) return; const s=await getNotificationSettings(db); const at=new Date(`${a.date}T${a.time || "09:00"}:00`).getTime(); for(const [kind,enabled,offset] of [["reminder_1","notifications.first_reminder_enabled","notifications.first_reminder_offset_minutes"],["reminder_2","notifications.second_reminder_enabled","notifications.second_reminder_offset_minutes"]] as const) if(s[enabled]==="1") { const due=new Date(at-Number(s[offset])*60000); if(due.getTime()>Date.now()) await queueAppointmentNotifications(db,appointmentId,kind,due.toISOString()); } }
export async function queueEventOperationalNotification(db:D1Database,input:{eventName:string;date:string;appointmentCount:number;actor:string;adminUrl:string}) { const {results}=await db.prepare("SELECT u.id,u.email FROM users u LEFT JOIN admin_notification_preferences p ON p.user_id=u.id WHERE u.role='admin' AND COALESCE(p.event_operational_email_enabled,1)=1").all<{id:number;email:string}>(); for(const admin of results) await insertJob(db,{userId:admin.id,kind:"event_cancelled",channel:"email",recipient:admin.email,scheduledAt:new Date().toISOString(),payload:input}); }
export async function processDueNotificationJobs(db:D1Database, env:NotificationEnvironment) { const settings=await getNotificationSettings(db); const providers=getNotificationProviderStatuses(settings,env); const {results}=await db.prepare("SELECT * FROM notification_jobs WHERE status='pending' AND datetime(scheduled_at)<=CURRENT_TIMESTAMP ORDER BY id LIMIT 50").all<any>(); for(const job of results) { const claimed=await db.prepare("UPDATE notification_jobs SET status='processing',attempts=attempts+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'").bind(job.id).run(); if(!claimed.meta.changes) continue; try { if(job.user_id && job.channel==='sms' && !(await smsAllowed(db,job.user_id))) { await mark(db,job.id,'cancelled'); continue; } const payload=JSON.parse(job.payload_json); const content=render(job.notification_type,job.channel,payload,env.APP_BASE_URL); const result=job.channel==='email' ? await createResendEmailProvider({apiKey:env.RESEND_API_KEY,from:formatSender(providers.email.senderName!,providers.email.senderAddress!)}).send({to:job.recipient,subject:content.subject!,text:content.text,replyTo:providers.email.replyTo||undefined}) : await createTelnyxSmsProvider({apiKey:env.TELNYX_API_KEY,from:providers.sms.senderNumber}).send({to:job.recipient,text:content.text}); await db.prepare("UPDATE notification_jobs SET status='sent',sent_at=CURRENT_TIMESTAMP,provider_message_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='processing'").bind(result.providerMessageId||null,job.id).run(); } catch(error) { await db.prepare("UPDATE notification_jobs SET status=CASE WHEN attempts >= 3 THEN 'failed' ELSE 'pending' END,last_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(error instanceof Error?error.message:"Unknown delivery error",job.id).run(); } } }
export async function handleSmsKeyword(db:D1Database,from:string,body:string) { const keyword=body.trim().toUpperCase(); if(!["STOP","START","HELP"].includes(keyword)) return null; const user=await db.prepare("SELECT id FROM users WHERE REPLACE(REPLACE(REPLACE(REPLACE(phone,' ',''),'-',''),'(',''),')','') LIKE ? ORDER BY id LIMIT 1").bind(`%${from.replace(/\D/g,"").slice(-10)}`).first<{id:number}>(); if(!user) return keyword; if(keyword==='STOP') await db.prepare("INSERT INTO user_notification_preferences(user_id,appointment_sms_enabled,sms_opted_out_at,updated_at) VALUES (?,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET appointment_sms_enabled=0,sms_opted_out_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP").bind(user.id).run(); if(keyword==='START') await db.prepare("UPDATE user_notification_preferences SET appointment_sms_enabled=1,sms_consent_at=CURRENT_TIMESTAMP,sms_consent_source='telnyx-start',sms_opted_out_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE user_id=?").bind(user.id).run(); return keyword; }
async function loadAppointment(db:D1Database,id:number) { return db.prepare(`SELECT a.id,a.user_id AS userId,COALESCE(NULLIF(TRIM(u.first_name||' '||u.last_name),''),u.email) AS name,u.email,u.phone,a.appointment_date AS date,a.appointment_time AS time,t.name AS loadType,d.event_name AS eventName FROM appointments a JOIN users u ON u.id=a.user_id JOIN dropoff_types t ON t.id=a.dropoff_type_id LEFT JOIN dropoff_days d ON d.dropoff_date=a.appointment_date WHERE a.id=?`).bind(id).first<Appointment>(); }
async function preferences(db:D1Database,userId:number,s:Record<string,string>):Promise<Preferences>{await db.prepare("INSERT INTO user_notification_preferences(user_id) VALUES(?) ON CONFLICT(user_id) DO NOTHING").bind(userId).run();const p=await db.prepare("SELECT appointment_email_enabled AS appointmentEmailEnabled,appointment_sms_enabled AS appointmentSmsEnabled,sms_opted_out_at AS smsOptedOutAt FROM user_notification_preferences WHERE user_id=?").bind(userId).first<any>();return {...p,emailEnabled:s["notifications.email_enabled"],smsEnabled:s["notifications.sms_enabled"]};}
async function smsAllowed(db:D1Database,userId:number){const p=await getNotificationPreferences(db,userId);const s=await getNotificationSettings(db);return Boolean(p?.appointmentSmsEnabled&&!p.smsOptedOutAt&&s["notifications.sms_enabled"]==="1");}
async function insertJob(db:D1Database,input:{userId?:number;appointmentId?:number;kind:string;channel:"email"|"sms";recipient:string;scheduledAt:string;payload:unknown}){const key=`${input.kind}:${input.appointmentId||"event"}:${input.channel}:${input.recipient}:${input.scheduledAt}`;await db.prepare("INSERT INTO notification_jobs(idempotency_key,user_id,appointment_id,notification_type,channel,recipient,payload_json,scheduled_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(idempotency_key) DO NOTHING").bind(key,input.userId||null,input.appointmentId||null,input.kind,input.channel,input.recipient,JSON.stringify(input.payload),input.scheduledAt).run();}
async function mark(db:D1Database,id:number,status:string){await db.prepare("UPDATE notification_jobs SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(status,id).run();}
function appointmentLink(a:Appointment,kind:string){return {name:a.name,date:a.date,time:a.time||"Time TBD",loadType:a.loadType,location:a.eventName||"Trice Auctions drop-off location",kind,appointmentId:a.id};}
function render(kind:string,channel:string,p:any,base=""){const url=`${base.replace(/\/$/,"")}/my-appointments${p.appointmentId?`/${p.appointmentId}`:""}`;if(kind==='event_cancelled')return {subject:`Action needed: ${p.eventName} was cancelled/closed`,text:`Trice Auctions: ${p.eventName} on ${p.date} was cancelled/closed by ${p.actor}. ${p.appointmentCount} scheduled appointment(s) are affected. Review: ${base}${p.adminUrl}`};const label=kind==='confirmation'?"confirmed":kind==='rescheduled'?"rescheduled":kind==='cancelled'?"cancelled":"reminder";const text=`Trice Auctions: Your drop-off appointment is ${label}${kind==='cancelled'?".":` for ${p.date} at ${p.time}.`} ${kind==='cancelled'?"":`Location: ${p.location}. ${url}`} Reply STOP to opt out.`;return channel==='sms'?{text}:{subject:kind==='confirmation'?"Your Trice Auctions Drop-Off Appointment is Confirmed":`Your Trice Auctions appointment was ${label}`,text:`Hello ${p.name},\n\n${text}\n\nLoad type: ${p.loadType}. Please arrive on time and bring your items ready for drop-off.`};}
function validPhone(phone:string|null){return Boolean(phone&&phone.replace(/\D/g,"").length>=10);}
function formatSender(name:string,address:string){return name ? `${name} <${address}>` : address;}
