import { createResendEmailProvider } from "./email-provider.server";
import { createTelnyxSmsProvider } from "./sms-provider.server";
import { TEMPLATE_PLACEHOLDERS, TEMPLATE_TYPES, renderTemplateText, unknownTemplatePlaceholders } from "../lib/notification-template.js";
import { getInternalAppointmentSnapshot, queueInternalAppointmentActivity, type AppointmentActivitySnapshot } from "./internal-appointment-notifications.server";

export type NotificationEnvironment = { RESEND_API_KEY?: string; RESEND_FROM_EMAIL?: string; TELNYX_API_KEY?: string; TELNYX_FROM_NUMBER?: string; TELNYX_WEBHOOK_PUBLIC_KEY?: string; APP_BASE_URL?: string };
type Preferences = { appointmentEmailEnabled: number; appointmentSmsEnabled: number; smsOptedOutAt: string | null; emailEnabled: string; smsEnabled: string };
type Appointment = { id: number; userId: number; firstName: string; lastName: string; name: string; email: string; phone: string | null; date: string; loadType: string; eventName: string | null };
type TemplateType = typeof TEMPLATE_TYPES[number];

export type NotificationProviderStatus = { provider: "resend" | "telnyx"; status: "Configured" | "Missing API Key" | "Missing Sender Address" | "Missing Sender Number" | "Missing Required Provider Configuration"; configured: boolean; senderName?: string; senderAddress?: string; replyTo?: string; senderNumber?: string; messagingProfileId?: string; inboundWebhook: { endpoint: string; signatureValidationConfigured: boolean } };
const settingsDefaults = { "notifications.first_reminder_enabled": "1", "notifications.first_reminder_offset_minutes": "10080", "notifications.second_reminder_enabled": "1", "notifications.second_reminder_offset_minutes": "1440", "notifications.email_enabled": "1", "notifications.sms_enabled": "1", "notifications.email_provider": "resend", "notifications.email_sender_name": "Trice Auctions", "notifications.email_sender_address": "", "notifications.email_reply_to": "", "notifications.sms_provider": "telnyx", "notifications.sms_sender_number": "", "notifications.sms_messaging_profile_id": "", "notifications.business_name": "Trice Auctions", "notifications.business_phone": "", "notifications.business_address": "" };
export async function getNotificationSettings(db: D1Database) { const { results } = await db.prepare("SELECT key, value FROM settings WHERE key LIKE 'notifications.%'").all<{key:string;value:string}>(); return { ...settingsDefaults, ...Object.fromEntries(results.map(x => [x.key, x.value])) }; }
export async function saveNotificationSettings(db: D1Database, values: Record<string, string>) { await db.batch(Object.entries(values).map(([key,value]) => db.prepare("INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(key,value))); }
export async function getNotificationTemplates(db: D1Database) { const { results } = await db.prepare("SELECT notification_type AS notificationType, channel, subject, body FROM notification_templates ORDER BY notification_type, channel").all<{ notificationType: TemplateType; channel: "email" | "sms"; subject: string | null; body: string }>(); return results; }
export { TEMPLATE_PLACEHOLDERS, TEMPLATE_TYPES };
export function validateNotificationTemplate(value: string) { const unknown = unknownTemplatePlaceholders(value); return unknown.length ? `Unsupported placeholder${unknown.length > 1 ? "s" : ""}: ${[...new Set(unknown)].join(", ")}.` : null; }
export async function saveNotificationTemplate(db: D1Database, input: { notificationType: TemplateType; channel: "email" | "sms"; subject?: string; body: string }) { const error = validateNotificationTemplate(`${input.subject || ""}\n${input.body}`); if (error) return { ok: false as const, error }; if (!input.body.trim()) return { ok: false as const, error: "Template body is required." }; await db.prepare("INSERT INTO notification_templates(notification_type,channel,subject,body,updated_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(notification_type,channel) DO UPDATE SET subject=excluded.subject,body=excluded.body,updated_at=CURRENT_TIMESTAMP").bind(input.notificationType,input.channel,input.channel === "email" ? input.subject || "" : null,input.body).run(); return { ok: true as const }; }
export function getNotificationProviderStatuses(settings: Record<string, string>, env: NotificationEnvironment): { email: NotificationProviderStatus; sms: NotificationProviderStatus } {
  const emailProvider = settings["notifications.email_provider"] === "resend" ? "resend" : "resend";
  const smsProvider = settings["notifications.sms_provider"] === "telnyx" ? "telnyx" : "telnyx";
  const senderAddress = settings["notifications.email_sender_address"].trim() || env.RESEND_FROM_EMAIL?.trim() || "";
  const senderNumber = settings["notifications.sms_sender_number"].trim() || env.TELNYX_FROM_NUMBER?.trim() || "";
  const emailStatus = !env.RESEND_API_KEY ? "Missing API Key" : !senderAddress ? "Missing Sender Address" : "Configured";
  const smsStatus = !env.TELNYX_API_KEY ? "Missing API Key" : !senderNumber ? "Missing Sender Number" : "Configured";
  return { email: { provider: emailProvider, status: emailStatus, configured: emailStatus === "Configured", senderName: settings["notifications.email_sender_name"], senderAddress, replyTo: settings["notifications.email_reply_to"], inboundWebhook: { endpoint: "", signatureValidationConfigured: false } }, sms: { provider: smsProvider, status: smsStatus, configured: smsStatus === "Configured", senderNumber, messagingProfileId: settings["notifications.sms_messaging_profile_id"], inboundWebhook: { endpoint: "/webhooks/telnyx/sms", signatureValidationConfigured: Boolean(env.TELNYX_WEBHOOK_PUBLIC_KEY) } } };
}
export async function sendTestNotification(db: D1Database, env: NotificationEnvironment, input: { channel: "email" | "sms"; destination: string; subject?: string; notificationType?: TemplateType }) {
  const settings = await getNotificationSettings(db);
  const providers = getNotificationProviderStatuses(settings, env);
  if (input.channel === "email") {
    if (!providers.email.configured) throw new Error(`Email testing unavailable: ${providers.email.status}.`);
    const content = await renderTemplate(db, input.notificationType || "confirmation", "email", sampleTemplateContext(env));
    return createResendEmailProvider({ apiKey: env.RESEND_API_KEY, from: formatSender(providers.email.senderName || "", providers.email.senderAddress || "") }).send({ to: input.destination, subject: input.subject || content.subject || "Trice Auctions Notification Test", text: content.text, replyTo: providers.email.replyTo || undefined });
  }
  if (!providers.sms.configured) throw new Error(`SMS testing unavailable: ${providers.sms.status}.`);
  const content = await renderTemplate(db, input.notificationType || "confirmation", "sms", sampleTemplateContext(env));
  return createTelnyxSmsProvider({ apiKey: env.TELNYX_API_KEY, from: providers.sms.senderNumber }).send({ to: input.destination, text: content.text });
}
export async function getNotificationPreferences(db: D1Database, userId: number) { await db.prepare("INSERT INTO user_notification_preferences(user_id) VALUES (?) ON CONFLICT(user_id) DO NOTHING").bind(userId).run(); return db.prepare("SELECT appointment_email_enabled AS appointmentEmailEnabled, appointment_sms_enabled AS appointmentSmsEnabled, sms_consent_at AS smsConsentAt, sms_consent_source AS smsConsentSource, sms_opted_out_at AS smsOptedOutAt FROM user_notification_preferences WHERE user_id=?").bind(userId).first<{appointmentEmailEnabled:number;appointmentSmsEnabled:number;smsConsentAt:string|null;smsConsentSource:string|null;smsOptedOutAt:string|null}>(); }
export async function updateNotificationPreferences(db:D1Database,userId:number,input:{emailEnabled:boolean;smsEnabled:boolean;source:string;hasValidPhone:boolean}) { if (input.smsEnabled && !input.hasValidPhone) return {ok:false as const,error:"Add a valid phone number before enabling SMS notifications."}; await db.prepare(`INSERT INTO user_notification_preferences(user_id,appointment_email_enabled,appointment_sms_enabled,sms_consent_at,sms_consent_source,sms_opted_out_at,updated_at) VALUES (?,?,?,?,?,CASE WHEN ? THEN NULL ELSE NULL END,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET appointment_email_enabled=excluded.appointment_email_enabled, appointment_sms_enabled=excluded.appointment_sms_enabled, sms_consent_at=CASE WHEN excluded.appointment_sms_enabled=1 AND user_notification_preferences.appointment_sms_enabled=0 THEN CURRENT_TIMESTAMP ELSE user_notification_preferences.sms_consent_at END, sms_consent_source=CASE WHEN excluded.appointment_sms_enabled=1 THEN excluded.sms_consent_source ELSE user_notification_preferences.sms_consent_source END, sms_opted_out_at=CASE WHEN excluded.appointment_sms_enabled=1 THEN NULL ELSE user_notification_preferences.sms_opted_out_at END,updated_at=CURRENT_TIMESTAMP`).bind(userId,input.emailEnabled?1:0,input.smsEnabled?1:0,input.smsEnabled?new Date().toISOString():null,input.source,input.smsEnabled?1:0,input.smsEnabled?1:0).run(); return {ok:true as const}; }

export async function queueAppointmentNotifications(db:D1Database, appointmentId:number, kind:"confirmation"|"rescheduled"|"cancelled"|"waitlisted"|"waitlist_confirmed"|"waitlist_cancelled"|"reminder_1"|"reminder_2", scheduledAt = new Date().toISOString()) { const appointment=await loadAppointment(db,appointmentId); if(!appointment) return; const settings=await getNotificationSettings(db); const prefs=await preferences(db,appointment.userId,settings); const base=appointmentLink(appointment,kind); if(settings["notifications.email_enabled"]==="1"&&prefs.appointmentEmailEnabled) await insertJob(db,{userId:appointment.userId,appointmentId,kind,channel:"email",recipient:appointment.email,scheduledAt,payload:base}); if(settings["notifications.sms_enabled"]==="1"&&prefs.appointmentSmsEnabled&&!prefs.smsOptedOutAt&&validPhone(appointment.phone)) await insertJob(db,{userId:appointment.userId,appointmentId,kind,channel:"sms",recipient:appointment.phone!,scheduledAt,payload:base}); }
export async function queueAppointmentCreated(db:D1Database,appointmentId:number,env?:NotificationEnvironment,actorName?:string,status:"scheduled"|"waitlisted"="scheduled") { const kind=status === "waitlisted" ? "waitlisted" : "confirmation"; await queueAppointmentNotifications(db,appointmentId,kind); if(status === "scheduled") await scheduleReminders(db,appointmentId); await queueInternalAppointmentActivity(db,{appointmentId,event:"created",actorName}); console.info("Appointment notification queued", { appointmentId, status }); if (env) await processDueNotificationJobs(db,env); }
export async function queueAppointmentRescheduled(db:D1Database,appointmentId:number,options: { previous?: AppointmentActivitySnapshot | null; actorName?: string; notifyCustomer?: boolean } = {}) { if (options.notifyCustomer !== false) { await cancelFutureAppointmentReminders(db,appointmentId); await queueAppointmentNotifications(db,appointmentId,"rescheduled"); await scheduleReminders(db,appointmentId); } await queueInternalAppointmentActivity(db,{appointmentId,event:"updated",previous:options.previous,actorName:options.actorName}); }
export async function queueAppointmentCancelled(db:D1Database,appointmentId:number,env?:NotificationEnvironment,actorName?:string,previous?:AppointmentActivitySnapshot|null) { await cancelFutureAppointmentReminders(db,appointmentId); await queueAppointmentNotifications(db,appointmentId,"cancelled"); await queueInternalAppointmentActivity(db,{appointmentId,event:"cancelled",previous,actorName}); console.info("Appointment cancellation notification queued", { appointmentId }); if (env) await processDueNotificationJobs(db,env); }
export async function cancelScheduledAppointment(db: D1Database, appointmentId: number, env?: NotificationEnvironment, actorName?: string) { const previous = await getInternalAppointmentSnapshot(db, appointmentId); const result = await db.prepare("UPDATE appointments SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='scheduled'").bind(appointmentId).run(); if (!result.meta.changes) return { cancelled: false as const }; await queueAppointmentCancelled(db, appointmentId, env, actorName, previous); return { cancelled: true as const }; }
export async function cancelWaitlistableAppointment(db: D1Database, appointmentId: number, env?: NotificationEnvironment, actorName?: string) { const previous = await getInternalAppointmentSnapshot(db, appointmentId); const appointment = await db.prepare("SELECT status FROM appointments WHERE id=?").bind(appointmentId).first<{status:string}>(); if (!appointment || !["scheduled", "waitlisted"].includes(appointment.status)) return { cancelled: false as const }; const result = await db.prepare("UPDATE appointments SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status=?").bind(appointmentId, appointment.status).run(); if (!result.meta.changes) return { cancelled: false as const }; if (appointment.status === "waitlisted") { await cancelFutureAppointmentReminders(db, appointmentId); await queueAppointmentNotifications(db, appointmentId, "waitlist_cancelled"); await queueInternalAppointmentActivity(db,{appointmentId,event:"cancelled",previous,actorName}); if (env) await processDueNotificationJobs(db,env); } else await queueAppointmentCancelled(db, appointmentId, env, actorName, previous); return { cancelled: true as const }; }
export async function cancelFutureAppointmentReminders(db:D1Database,appointmentId:number) { await db.prepare("UPDATE notification_jobs SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE appointment_id=? AND notification_type IN ('reminder_1','reminder_2') AND status IN ('pending','processing')").bind(appointmentId).run(); }
async function scheduleReminders(db:D1Database,appointmentId:number) { const a=await loadAppointment(db,appointmentId); if(!a) return; const s=await getNotificationSettings(db); const notificationAnchor=new Date(`${a.date}T09:00:00`).getTime(); for(const [kind,enabled,offset] of [["reminder_1","notifications.first_reminder_enabled","notifications.first_reminder_offset_minutes"],["reminder_2","notifications.second_reminder_enabled","notifications.second_reminder_offset_minutes"]] as const) if(s[enabled]==="1") { const due=new Date(notificationAnchor-Number(s[offset])*60000); if(due.getTime()>Date.now()) await queueAppointmentNotifications(db,appointmentId,kind,due.toISOString()); } }
export async function queueEventOperationalNotification(db:D1Database,input:{eventName:string;date:string;appointmentCount:number;actor:string;adminUrl:string}) { const {results}=await db.prepare("SELECT u.id,u.email FROM users u LEFT JOIN admin_notification_preferences p ON p.user_id=u.id WHERE u.role='admin' AND COALESCE(p.event_operational_email_enabled,1)=1").all<{id:number;email:string}>(); for(const admin of results) await insertJob(db,{userId:admin.id,kind:"event_cancelled",channel:"email",recipient:admin.email,scheduledAt:new Date().toISOString(),payload:input}); }
export async function processDueNotificationJobs(db:D1Database, env:NotificationEnvironment) { const settings=await getNotificationSettings(db); const providers=getNotificationProviderStatuses(settings,env); const {results}=await db.prepare("SELECT * FROM notification_jobs WHERE status='pending' AND datetime(scheduled_at)<=CURRENT_TIMESTAMP ORDER BY id LIMIT 50").all<any>(); for(const job of results) { const claimed=await db.prepare("UPDATE notification_jobs SET status='processing',attempts=attempts+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'").bind(job.id).run(); if(!claimed.meta.changes) continue; try { if(job.user_id && job.channel==='sms' && !(await smsAllowed(db,job.user_id))) { await mark(db,job.id,'cancelled'); console.info("Notification suppressed by SMS preference", { jobId: job.id }); continue; } const payload=JSON.parse(job.payload_json); const content=job.notification_type.startsWith("internal_") ? renderInternalAppointmentActivity(payload,env.APP_BASE_URL) : job.appointment_id ? await renderTemplate(db,job.notification_type,job.channel,await appointmentTemplateContext(db,job.appointment_id,env)) : renderEvent(job.notification_type,payload,env.APP_BASE_URL); const result=job.channel==='email' ? await createResendEmailProvider({apiKey:env.RESEND_API_KEY,from:formatSender(providers.email.senderName!,providers.email.senderAddress!)}).send({to:job.recipient,subject:content.subject!,text:content.text,replyTo:providers.email.replyTo||undefined}) : await createTelnyxSmsProvider({apiKey:env.TELNYX_API_KEY,from:providers.sms.senderNumber}).send({to:job.recipient,text:content.text}); await db.prepare("UPDATE notification_jobs SET status='sent',sent_at=CURRENT_TIMESTAMP,provider_message_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='processing'").bind(result.providerMessageId||null,job.id).run(); console.info("Notification sent", { jobId: job.id, type: job.notification_type, channel: job.channel }); } catch(error) { const message=error instanceof Error?error.message:"Unknown delivery error"; await db.prepare("UPDATE notification_jobs SET status=CASE WHEN attempts >= 3 THEN 'failed' ELSE 'pending' END,last_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(message,job.id).run(); console.error("Notification failed", { jobId: job.id, type: job.notification_type, channel: job.channel, error: message }); } } }
export async function handleSmsKeyword(db:D1Database,from:string,body:string) { const keyword=body.trim().toUpperCase(); if(!["STOP","START","HELP"].includes(keyword)) return null; const user=await db.prepare("SELECT id FROM users WHERE REPLACE(REPLACE(REPLACE(REPLACE(phone,' ',''),'-',''),'(',''),')','') LIKE ? ORDER BY id LIMIT 1").bind(`%${from.replace(/\D/g,"").slice(-10)}`).first<{id:number}>(); if(!user) return keyword; if(keyword==='STOP') await db.prepare("INSERT INTO user_notification_preferences(user_id,appointment_sms_enabled,sms_opted_out_at,updated_at) VALUES (?,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET appointment_sms_enabled=0,sms_opted_out_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP").bind(user.id).run(); if(keyword==='START') await db.prepare("UPDATE user_notification_preferences SET appointment_sms_enabled=1,sms_consent_at=CURRENT_TIMESTAMP,sms_consent_source='telnyx-start',sms_opted_out_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE user_id=?").bind(user.id).run(); return keyword; }
async function loadAppointment(db:D1Database,id:number) { return db.prepare(`SELECT a.id,a.user_id AS userId,COALESCE(u.first_name,'') AS firstName,COALESCE(u.last_name,'') AS lastName,COALESCE(NULLIF(TRIM(u.first_name||' '||u.last_name),''),u.email) AS name,u.email,u.phone,a.appointment_date AS date,t.name AS loadType,d.event_name AS eventName FROM appointments a JOIN users u ON u.id=a.user_id JOIN dropoff_types t ON t.id=a.dropoff_type_id LEFT JOIN dropoff_days d ON d.dropoff_date=a.appointment_date WHERE a.id=?`).bind(id).first<Appointment>(); }
async function preferences(db:D1Database,userId:number,s:Record<string,string>):Promise<Preferences>{await db.prepare("INSERT INTO user_notification_preferences(user_id) VALUES(?) ON CONFLICT(user_id) DO NOTHING").bind(userId).run();const p=await db.prepare("SELECT appointment_email_enabled AS appointmentEmailEnabled,appointment_sms_enabled AS appointmentSmsEnabled,sms_opted_out_at AS smsOptedOutAt FROM user_notification_preferences WHERE user_id=?").bind(userId).first<any>();return {...p,emailEnabled:s["notifications.email_enabled"],smsEnabled:s["notifications.sms_enabled"]};}
async function smsAllowed(db:D1Database,userId:number){const p=await getNotificationPreferences(db,userId);const s=await getNotificationSettings(db);return Boolean(p?.appointmentSmsEnabled&&!p.smsOptedOutAt&&s["notifications.sms_enabled"]==="1");}
async function insertJob(db:D1Database,input:{userId?:number;appointmentId?:number;kind:string;channel:"email"|"sms";recipient:string;scheduledAt:string;payload:unknown}){const key=`${input.kind}:${input.appointmentId||"event"}:${input.channel}:${input.recipient}:${input.scheduledAt}`;await db.prepare("INSERT INTO notification_jobs(idempotency_key,user_id,appointment_id,notification_type,channel,recipient,payload_json,scheduled_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(idempotency_key) DO NOTHING").bind(key,input.userId||null,input.appointmentId||null,input.kind,input.channel,input.recipient,JSON.stringify(input.payload),input.scheduledAt).run();}
async function mark(db:D1Database,id:number,status:string){await db.prepare("UPDATE notification_jobs SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(status,id).run();}
function appointmentLink(a:Appointment,kind:string){return {name:a.name,date:a.date,loadType:a.loadType,location:a.eventName||"Trice Auctions drop-off location",kind,appointmentId:a.id};}
async function appointmentTemplateContext(db:D1Database,id:number,env:NotificationEnvironment){const a=await loadAppointment(db,id);if(!a)throw new Error("Appointment is unavailable for notification delivery.");const settings=await getNotificationSettings(db);return {first_name:a.firstName||a.name,last_name:a.lastName,appointment_date:a.date,appointment_link:`${(env.APP_BASE_URL||"").replace(/\/$/,"")}/my-appointments/${a.id}`,event_name:a.eventName||"Trice Auctions Drop-Off",load_type:a.loadType,business_name:settings["notifications.business_name"]||"Trice Auctions",business_phone:settings["notifications.business_phone"]||"",business_address:settings["notifications.business_address"]||""};}
function sampleTemplateContext(env:NotificationEnvironment){return {first_name:"Alex",last_name:"Customer",appointment_date:"November 4, 2026",appointment_link:`${(env.APP_BASE_URL||"https://example.com").replace(/\/$/,"")}/my-appointments/123`,event_name:"Fall Drop-Off Event",load_type:"Car Load",business_name:"Trice Auctions",business_phone:"(555) 555-0123",business_address:"123 Auction Lane"};}
async function renderTemplate(db:D1Database,type:string,channel:string,context:Record<string,string>){const template=await db.prepare("SELECT subject,body FROM notification_templates WHERE notification_type=? AND channel=?").bind(type,channel).first<{subject:string|null;body:string}>();if(!template)throw new Error("Notification template is unavailable.");return {subject:template.subject?renderTemplateText(template.subject,context):undefined,text:renderTemplateText(template.body,context)};}
function renderEvent(kind:string,p:any,base=""){return {subject:`Action needed: ${p.eventName} was cancelled/closed`,text:`Trice Auctions: ${p.eventName} on ${p.date} was cancelled/closed by ${p.actor}. ${p.appointmentCount} scheduled appointment(s) are affected. Review: ${base}${p.adminUrl}`};}
function renderInternalAppointmentActivity(payload: { event: "created" | "updated" | "cancelled"; current: AppointmentActivitySnapshot; previous?: AppointmentActivitySnapshot | null; actorName?: string | null; occurredAt: string }, base = "") { const { current, previous } = payload; const detail = `${base.replace(/\/$/, "")}/admin/appointments/${current.id}`; const allocationText = current.allocations.map((item) => `${item.name}: ${item.percentage}%`).join(" · ") || "No area allocations"; const lines = ["Trice Auctions internal appointment activity", "", `Customer: ${current.customerName}`, `Email: ${current.customerEmail}`, `Phone: ${current.customerPhone || "Not provided"}`, `Appointment ID: ${current.id}`, `Drop-off date: ${current.date}`, `Load type: ${current.loadType}`, `Areas: ${allocationText}`, `Description: ${current.description || "No description provided."}`]; if (previous) lines.push("", "Previous details:", `Date: ${previous.date}`, `Load type: ${previous.loadType}`, `Areas: ${previous.allocations.map((item) => `${item.name}: ${item.percentage}%`).join(" · ") || "No area allocations"}`, `Description: ${previous.description || "No description provided."}`); if (payload.event === "cancelled") lines.push(`Cancellation timestamp: ${payload.occurredAt}`); if (payload.actorName) lines.push(`Changed by: ${payload.actorName}`); lines.push("", `Review appointment: ${detail}`); const label = payload.event === "created" ? "New appointment" : payload.event === "updated" ? "Appointment updated" : "Appointment cancelled"; return { subject: `Trice Auctions: ${label} #${current.id}`, text: lines.join("\n") }; }
function validPhone(phone:string|null){return Boolean(phone&&phone.replace(/\D/g,"").length>=10);}
function formatSender(name:string,address:string){return name ? `${name} <${address}>` : address;}
