import { env } from "cloudflare:workers";
import { Link } from "react-router";
import type { Route } from "./+types/admin.booking-events";
import { requireRole } from "../services/auth.server";
import { PageCard, PageIntro, PageShell } from "../components/design-system";
import { bookingEventInstant, formatBookingEventTime } from "../lib/booking-event-time";
const runtime = env as unknown as { AUTH_SECRET?: string; BETTER_AUTH_URL?: string };
export async function loader({ request }: Route.LoaderArgs) {
  await requireRole(request, env.trice_auction_db, runtime, "admin");
  const [{ results: bookingEvents }, { results: dates }] = await Promise.all([
    env.trice_auction_db.prepare(`SELECT event.id, event.name, event.description, event.opens_at AS opensAt, event.closes_at AS closesAt, event.timezone, event.timestamp_storage_version AS timeStorageVersion, event.active, COUNT(day.id) AS dropoffDateCount, COALESCE(SUM((SELECT COUNT(*) FROM appointments appointment WHERE appointment.appointment_date = day.dropoff_date)), 0) AS appointmentCount FROM booking_events event LEFT JOIN booking_event_dropoff_dates link ON link.booking_event_id = event.id LEFT JOIN dropoff_days day ON day.id = link.dropoff_day_id GROUP BY event.id ORDER BY event.opens_at DESC`).all<{id:number;name:string;description:string|null;opensAt:string;closesAt:string|null;timezone:string;timeStorageVersion:number;active:number;dropoffDateCount:number;appointmentCount:number}>(),
    env.trice_auction_db.prepare(`SELECT link.booking_event_id AS bookingEventId, day.id, day.dropoff_date AS date, day.event_name AS name, day.is_open AS isOpen, COUNT(appointment.id) AS appointmentCount FROM booking_event_dropoff_dates link JOIN dropoff_days day ON day.id = link.dropoff_day_id LEFT JOIN appointments appointment ON appointment.appointment_date = day.dropoff_date AND appointment.status = 'scheduled' GROUP BY link.booking_event_id, day.id ORDER BY day.dropoff_date`).all<{bookingEventId:number;id:number;date:string;name:string|null;isOpen:number;appointmentCount:number}>(),
  ]);
  const datesByBookingEvent = new Map<number, typeof dates>();
  for (const date of dates) datesByBookingEvent.set(date.bookingEventId, [...(datesByBookingEvent.get(date.bookingEventId) ?? []), date]);
  return { bookingEvents: bookingEvents.map(event => ({ ...event, status: status(event), dates: datesByBookingEvent.get(event.id) ?? [] })) };
}
function status(event: { active:number; opensAt:string; closesAt:string|null; timezone:string; timeStorageVersion:number }) { const opensAt=bookingEventInstant(event.opensAt,event.timezone,event.timeStorageVersion), closesAt=event.closesAt?bookingEventInstant(event.closesAt,event.timezone,event.timeStorageVersion):null; if (!event.active || !opensAt) return "Inactive"; if (Date.now() < opensAt.getTime()) return "Upcoming"; if (closesAt && Date.now() >= closesAt.getTime()) return "Closed"; return "Open"; }
export default function BookingEvents({ loaderData }: Route.ComponentProps) {
  return <PageShell><div className="max-w-6xl"><PageIntro eyebrow="Trice Auctions · Administration" title="Booking Events">Create customer-facing signup events and manage their Drop-Off Dates.</PageIntro><div className="mb-7"><Link to="/admin/booking-events/new" className="ta-button ta-button-primary">New Booking Event</Link></div>{loaderData.bookingEvents.length ? <section className="grid gap-5 lg:grid-cols-2">{loaderData.bookingEvents.map(event => <PageCard key={event.id} title={event.name}><div className="flex items-center justify-between gap-3"><p className="text-sm text-[#5f6368]">Opens {formatBookingEventTime(event.opensAt, event.timezone, event.timeStorageVersion)}</p><span className="rounded-full bg-stone-100 px-3 py-1 text-xs font-bold">{event.status}</span></div>{event.closesAt ? <p className="mt-1 text-sm text-[#5f6368]">Closes {formatBookingEventTime(event.closesAt, event.timezone, event.timeStorageVersion)}</p> : null}<p className="mt-4 text-sm text-[#5f6368]">{event.dropoffDateCount} Drop-Off Date{event.dropoffDateCount === 1 ? "" : "s"} · {event.appointmentCount} appointment{event.appointmentCount === 1 ? "" : "s"}</p><section className="mt-5 border-t border-[#dfe1e4] pt-4" aria-label={`${event.name} Drop-Off Dates`}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold text-[#25272b]">Drop-Off Dates</h2><Link to={`/admin/schedule/new?bookingEventId=${event.id}`} className="text-sm font-bold text-[#9d302f] underline">Add Drop-Off Date</Link></div>{event.dates.length ? <ul className="mt-3 space-y-2">{event.dates.map(date => <li key={date.id} className="rounded-lg border border-[#dfe1e4] bg-[#f8f9fa] p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-semibold text-[#25272b]">{date.date}</p><p className="text-sm text-[#5f6368]">{date.isOpen ? "Open" : "Closed"} · {date.appointmentCount} appointment{date.appointmentCount === 1 ? "" : "s"}</p></div><div className="flex gap-3 text-sm font-bold text-[#9d302f]"><Link className="underline" to={`/admin/schedule/${date.id}`}>Edit</Link><Link className="underline" to={`/admin/schedule/${date.id}#appointments`}>View Schedule</Link></div></div></li>)}</ul> : <p className="mt-3 text-sm text-[#5f6368]">No Drop-Off Dates have been added yet.</p>}</section><Link className="mt-5 inline-flex font-bold text-[#9d302f] underline" to={`/admin/booking-events/${event.id}`}>View / edit Booking Event</Link></PageCard>)}</section> : <PageCard title="No Booking Events Yet"><p className="text-[#5f6368]">Create a Booking Event, then add one or more public Drop-Off Dates.</p></PageCard>}</div></PageShell>;
}
