import { env } from "cloudflare:workers";
import { data, Form, Link, redirect } from "react-router";
import type { Route } from "./+types/admin.appointments.new";
import { createAppointmentOverrideAuditStatement } from "../services/appointment-override-audit.server";
import { createBooking, createBookingWithOverride, getBookingOptions, type BookingInput, validateBooking } from "../services/booking.server";
import { requireRole } from "../services/auth.server";
import { getCustomerById, searchCustomers } from "../services/customer-management.server";
import { getDropoffEventById } from "../services/schedule-management.server";

const runtime = env as unknown as { AUTH_SECRET?: string; BETTER_AUTH_URL?: string };

export async function loader({ request }: Route.LoaderArgs) {
  await requireRole(request, env.trice_auction_db, runtime, "admin");
  const url = new URL(request.url); const q = url.searchParams.get("q") ?? ""; const customerId = Number(url.searchParams.get("customerId")); const scheduleId = Number(url.searchParams.get("scheduleId")); const appointmentDate = url.searchParams.get("appointmentDate") ?? "";
  const [options, customers, selectedCustomer, schedule] = await Promise.all([getBookingOptions(env.trice_auction_db, { adminScheduling: true }), searchCustomers(env.trice_auction_db, q), Number.isInteger(customerId) && customerId > 0 ? getCustomerById(env.trice_auction_db, customerId) : null, Number.isInteger(scheduleId) && scheduleId > 0 ? getDropoffEventById(env.trice_auction_db, scheduleId) : null]);
  if (scheduleId && !schedule) throw new Response("Not Found", { status: 404 });
  const selectedDate = schedule ? { date: schedule.date, eventName: schedule.eventName, adminStatus: [] as string[] } : options.availableDates.find((date) => date.date === appointmentDate) ?? null;
  return { options, q, customers, selectedCustomer, selectedDate, scheduleId: schedule?.id ?? null };
}

export async function action({ request }: Route.ActionArgs) {
  const actor = await requireRole(request, env.trice_auction_db, runtime, "admin");
  const form = await request.formData(); const scheduleId = Number(form.get("scheduleId")); const hasScheduleContext = Number.isInteger(scheduleId) && scheduleId > 0; const schedule = hasScheduleContext ? await getDropoffEventById(env.trice_auction_db, scheduleId) : null; if (hasScheduleContext && !schedule) throw new Response("Not Found", { status: 404 }); const input = bookingInputFromForm(form);
  if (schedule) input.appointmentDate = schedule.date;
  const customer = await getCustomerById(env.trice_auction_db, input.userId);
  if (!customer) return data({ ok: false as const, errors: ["Choose an existing customer."], submitted: input }, { status: 400 });
  if (form.get("intent") !== "override") { const result = await createBooking(env.trice_auction_db, input, { allowAdminScheduling: true }); if (result.ok) return redirect(schedule ? `/admin/schedule/${schedule.id}?created=${result.appointmentId}` : `/admin/appointments?created=${result.appointmentId}`); return data({ ...result, submitted: input }, { status: 400 }); }
  const reason = String(form.get("overrideReason") || "").trim(); if (!reason) return data({ ok: false as const, errors: ["An override reason is required."], overridableViolations: [], submitted: input }, { status: 400 });
  const validation = await validateBooking(env.trice_auction_db, input, { allowAdminScheduling: true });
  if (validation.ok || !validation.dropoffType || !onlyOverridable(validation.errors, validation.overridableViolations)) return data({ ...(validation.ok ? { ok: false, errors: ["This appointment no longer requires an override."], overridableViolations: [] } : validation), submitted: input }, { status: 400 });
  const appointmentId = await createBookingWithOverride(env.trice_auction_db, input, validation.dropoffType);
  await createAppointmentOverrideAuditStatement(env.trice_auction_db, { appointmentId, actorUserId: actor.id, actorRole: "admin", reason, violatedRules: validation.overridableViolations, previousValues: null, requestedValues: input, capacityContext: validation.capacityContext }).run();
  return redirect(schedule ? `/admin/schedule/${schedule.id}?created=${appointmentId}` : `/admin/appointments/${appointmentId}`);
}

export default function NewAppointment({ loaderData, actionData }: Route.ComponentProps) {
  const submitted = actionData && "submitted" in actionData ? actionData.submitted : null;
  const needsOverride = actionData && !actionData.ok && "overridableViolations" in actionData && onlyOverridable(actionData.errors, actionData.overridableViolations);
  const customerId = submitted?.userId ?? loaderData.selectedCustomer?.id;
  const selectedDate = loaderData.selectedDate?.date ?? "";
  const scheduleId = loaderData.scheduleId;
  const appointmentPath = `/admin/appointments/new?appointmentDate=${selectedDate}${scheduleId ? `&scheduleId=${scheduleId}` : ""}`;
  const customerReturnTo = encodeURIComponent(appointmentPath);
  const backTo = scheduleId ? `/admin/schedule/${scheduleId}` : "/admin/appointments";
  return <main className="mx-auto max-w-4xl p-8"><Link to={backTo}>← {scheduleId ? "Drop-Off Date" : "Appointments"}</Link><h1 className="mt-4 text-3xl font-bold">New Appointment</h1><p className="mt-2 rounded border border-blue-200 bg-blue-50 p-3 text-sm text-blue-950">Admins may schedule appointments outside the public signup window. Capacity and customer booking limits still apply.</p>{scheduleId ? <p className="mt-3 rounded border border-violet-200 bg-violet-50 p-3 text-sm text-violet-950">Adding an appointment for <strong>{loaderData.selectedDate?.eventName || selectedDate}</strong> on {selectedDate}. The drop-off date is locked to this schedule.</p> : null}<Form method="get" className="mt-5 flex gap-2"><input type="hidden" name="appointmentDate" value={selectedDate}/>{scheduleId ? <input type="hidden" name="scheduleId" value={scheduleId}/> : null}<input name="q" defaultValue={loaderData.q} placeholder="Search name, email, or phone" className="w-full border p-2"/><button className="border px-3">Search</button><Link className="border px-3 py-2" to={`/admin/customers/new?returnTo=${customerReturnTo}`}>Create Customer</Link></Form><div className="mt-3 rounded border p-3">{loaderData.selectedCustomer ? <strong>Selected: {loaderData.selectedCustomer.name} · {loaderData.selectedCustomer.email}</strong> : loaderData.customers.length ? loaderData.customers.map((customer) => <Link key={customer.id} className="mr-3 inline-block underline" to={`${appointmentPath}&customerId=${customer.id}&q=${encodeURIComponent(loaderData.q)}`}>{customer.name} ({customer.email})</Link>) : <span>No customer found. Use Create Customer to add one.</span>}</div>{actionData && !actionData.ok ? <div className="mt-4 rounded border border-red-200 bg-red-50 p-3" role="alert">{actionData.errors.join(" ")}</div> : null}{customerId ? <AppointmentForm options={loaderData.options} customerId={customerId} submitted={submitted} selectedDate={selectedDate} scheduleId={scheduleId}/>: <p className="mt-6 text-stone-600">Select a customer before creating an appointment.</p>}{needsOverride && submitted ? <OverrideForm input={submitted} scheduleId={scheduleId}/>: null}</main>;
}

function AppointmentForm({ options, customerId, submitted, selectedDate, scheduleId }: { options: Awaited<ReturnType<typeof getBookingOptions>>; customerId: number; submitted: BookingInput | null; selectedDate?: string; scheduleId: number | null }) { return <Form method="post" className="mt-6 grid gap-4 rounded border bg-white p-5"><input type="hidden" name="intent" value="save"/><input type="hidden" name="customerId" value={customerId}/>{scheduleId ? <><input type="hidden" name="scheduleId" value={scheduleId}/><p className="font-semibold">Drop-Off Date: {selectedDate}</p></> : <label>Drop-Off Date<select required name="appointmentDate" defaultValue={submitted?.appointmentDate ?? selectedDate} className="mt-1 block w-full border p-2"><option value="">Choose a Drop-Off Date</option>{options.availableDates.map((date) => <option key={date.date} value={date.date}>{date.date}{date.eventName ? ` — ${date.eventName}` : ""}{date.adminStatus?.length ? ` [${date.adminStatus.join(" · ")}]` : ""}</option>)}</select></label>}<label>Load type<select required name="dropoffTypeId" defaultValue={submitted?.dropoffTypeId} className="mt-1 block border p-2"><option value="">Choose load</option>{options.dropoffTypes.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-3">{options.itemAreas.map((area, index) => <label key={area.id}>{area.name} percentage<input required min="0" max="100" type="number" name={`allocation-${area.id}`} defaultValue={submitted?.allocations.find((item) => item.itemAreaId === area.id)?.percentage ?? (index === 0 ? 100 : 0)} className="mt-1 block w-full border p-2"/></label>)}</div><label>Description<textarea name="description" defaultValue={submitted?.description || ""} className="mt-1 block w-full border p-2"/></label><button className="rounded bg-stone-900 px-4 py-2 font-semibold text-white">Create appointment</button></Form>; }
function OverrideForm({ input, scheduleId }: { input: BookingInput; scheduleId: number | null }) { return <Form method="post" className="mt-5 rounded border-2 border-amber-500 bg-amber-50 p-4"><input type="hidden" name="intent" value="override"/>{scheduleId ? <input type="hidden" name="scheduleId" value={scheduleId}/> : null}<input type="hidden" name="customerId" value={input.userId}/><input type="hidden" name="appointmentDate" value={input.appointmentDate}/><input type="hidden" name="dropoffTypeId" value={input.dropoffTypeId}/><input type="hidden" name="description" value={input.description}/>{input.allocations.map((item) => <input key={item.itemAreaId} type="hidden" name={`allocation-${item.itemAreaId}`} value={item.percentage}/>)}<label>Override reason<textarea required name="overrideReason" className="mt-1 block w-full border p-2"/></label><button className="mt-3 rounded bg-stone-900 px-4 py-2 font-semibold text-white">Record override and create appointment</button></Form>; }
function bookingInputFromForm(form: FormData): BookingInput { return { userId: Number(form.get("customerId")), appointmentDate: String(form.get("appointmentDate") || ""), dropoffTypeId: Number(form.get("dropoffTypeId")), description: String(form.get("description") || ""), allocations: Array.from(form.entries()).filter(([key]) => key.startsWith("allocation-")).map(([key, value]) => ({ itemAreaId: Number(key.slice(11)), percentage: Number(value) })) }; }
function onlyOverridable(errors: string[], overridable: string[]) { return errors.length > 0 && overridable.length > 0 && errors.every((error) => overridable.includes(error)); }
