import { env } from "cloudflare:workers";
import { Form, Link } from "react-router";
import type { Route } from "./+types/admin.appointments";
import { requireRole } from "../services/auth.server";
import { AppointmentStatusBadge } from "../components/admin-appointment-summary";
import { Button, PageCard, PageIntro, PageShell } from "../components/design-system";

const runtime = env as unknown as { AUTH_SECRET?: string; BETTER_AUTH_URL?: string };
export async function loader({ request }: Route.LoaderArgs) { await requireRole(request, env.trice_auction_db, runtime, "admin"); const q = new URL(request.url).searchParams.get("q")?.trim() ?? ""; const pattern = `%${q}%`; const { results } = await env.trice_auction_db.prepare(`SELECT a.id, a.appointment_date AS date, a.appointment_time AS time, a.status, d.name AS loadType, COALESCE(NULLIF(TRIM(u.first_name || ' ' || u.last_name), ''), u.email) AS customer, u.email FROM appointments a JOIN users u ON u.id = a.user_id JOIN dropoff_types d ON d.id = a.dropoff_type_id WHERE ? = '' OR LOWER(u.email) LIKE LOWER(?) OR LOWER(COALESCE(u.first_name, '') || ' ' || COALESCE(u.last_name, '')) LIKE LOWER(?) ORDER BY a.appointment_date DESC, a.appointment_time DESC, a.id DESC`).bind(q, pattern, pattern).all<{ id: number; date: string; time: string | null; status: string; loadType: string; customer: string; email: string }>(); return { q, appointments: results }; }

export default function AdminAppointments({ loaderData }: Route.ComponentProps) { return <PageShell><div className="max-w-7xl"><PageIntro eyebrow="Trice Auctions · Administration" title="Appointments">Search and manage customer drop-off appointments.</PageIntro><div className="mb-7 flex flex-wrap gap-3"><Link to="/admin/appointments/new" className="ta-button ta-button-primary">New Appointment</Link><Link to="/admin/schedule" className="ta-button ta-button-secondary">Manage Drop-Off Events</Link></div><PageCard title="Find Appointments"><Form method="get" className="flex flex-col gap-3 sm:flex-row"><input name="q" defaultValue={loaderData.q} placeholder="Customer name or email" className="min-h-11 flex-1 rounded-md border border-[#c9cdd2] bg-white px-3 py-2.5 outline-none focus:border-[#9d302f] focus:ring-2 focus:ring-[#f2d8d7]"/><Button variant="secondary">Search</Button></Form></PageCard><section className="mt-6 overflow-hidden rounded-xl border border-[#dfe1e4] bg-[#f8f9fa] shadow-sm" aria-label="Appointments"><div className="hidden grid-cols-[minmax(13rem,1.5fr)_minmax(10rem,1fr)_minmax(9rem,1fr)_auto_auto] gap-4 border-b border-[#dfe1e4] bg-[#9d302f] px-5 py-3 text-sm font-bold text-white lg:grid"><span>Customer</span><span>Date & time</span><span>Load type</span><span>Status</span><span className="sr-only">Actions</span></div>{loaderData.appointments.length ? <div className="divide-y divide-[#dfe1e4]">{loaderData.appointments.map((appointment) => <article key={appointment.id} className="grid gap-3 bg-white p-5 lg:grid-cols-[minmax(13rem,1.5fr)_minmax(10rem,1fr)_minmax(9rem,1fr)_auto_auto] lg:items-center lg:gap-4"><div><p className="font-bold text-[#25272b]">{appointment.customer}</p><p className="mt-1 text-sm text-[#5f6368]">{appointment.email}</p></div><p className="text-sm font-medium text-[#35383d]">{appointment.date} · {appointment.time || "Time TBD"}</p><p className="text-sm text-[#35383d]">{appointment.loadType}</p><div><AppointmentStatusBadge status={appointment.status}/></div><Link to={`/admin/appointments/${appointment.id}`} className="ta-button ta-button-secondary w-full sm:w-auto">View Appointment</Link></article>)}</div> : <div className="p-8 text-center"><p className="font-semibold text-[#25272b]">No appointments found.</p><p className="mt-2 text-sm text-[#5f6368]">Try a different customer name or email, or create a new appointment.</p></div>}</section></div></PageShell>; }
