import { env } from "cloudflare:workers";
import { Form, Link } from "react-router";
import type { Route } from "./+types/admin.appointments";
import { requireRole } from "../services/auth.server";
import { AdminAppointmentCard } from "../components/admin-appointment-summary";
import { Button, PageCard, PageIntro, PageShell } from "../components/design-system";

const runtime = env as unknown as { AUTH_SECRET?: string; BETTER_AUTH_URL?: string };
export async function loader({ request }: Route.LoaderArgs) { await requireRole(request, env.trice_auction_db, runtime, "admin"); const url = new URL(request.url); const q = url.searchParams.get("q")?.trim() ?? ""; const status = url.searchParams.get("status") ?? "all"; const pattern = `%${q}%`; const { results } = await env.trice_auction_db.prepare(`SELECT a.id, a.appointment_date AS date, a.status, d.name AS loadType, COALESCE(NULLIF(TRIM(u.first_name || ' ' || u.last_name), ''), u.email) AS customer, u.email, u.consignor_id AS consignorId, COALESCE(GROUP_CONCAT(area.name || ': ' || allocation.allocation_percent || '%', ' · '), '') AS allocationSummary FROM appointments a JOIN users u ON u.id = a.user_id JOIN dropoff_types d ON d.id = a.dropoff_type_id LEFT JOIN appointment_area_allocations allocation ON allocation.appointment_id = a.id LEFT JOIN item_areas area ON area.id = allocation.item_area_id WHERE (? = 'all' OR a.status = ?) AND (? = '' OR LOWER(u.email) LIKE LOWER(?) OR LOWER(COALESCE(u.first_name, '') || ' ' || COALESCE(u.last_name, '')) LIKE LOWER(?) OR LOWER(COALESCE(u.consignor_id, '')) LIKE LOWER(?)) GROUP BY a.id ORDER BY a.appointment_date DESC, a.id DESC`).bind(status, status, q, pattern, pattern, pattern).all<{ id: number; date: string; status: string; loadType: string; customer: string; email: string; consignorId: string | null; allocationSummary: string }>(); return { q, status, appointments: results }; }

export default function AdminAppointments({ loaderData }: Route.ComponentProps) { return <PageShell><div className="max-w-7xl"><PageIntro eyebrow="Trice Auctions · Administration" title="Appointments">Search and manage customer drop-off appointments.</PageIntro><div className="mb-7 flex flex-wrap gap-3"><Link to="/admin/appointments/new" className="ta-button ta-button-primary">New Appointment</Link><Link to="/admin/schedule" className="ta-button ta-button-secondary">Manage Drop-Off Events</Link></div><PageCard title="Find Appointments"><Form method="get" className="flex flex-col gap-3 sm:flex-row"><input name="q" defaultValue={loaderData.q} placeholder="Customer name, email, or Consignor ID" className="min-h-11 flex-1 rounded-md border border-[#c9cdd2] bg-white px-3 py-2.5 outline-none focus:border-[#9d302f] focus:ring-2 focus:ring-[#f2d8d7]"/><select name="status" defaultValue={loaderData.status} className="rounded-md border border-[#c9cdd2] bg-white px-3 py-2.5"><option value="all">All statuses</option><option value="scheduled">Scheduled</option><option value="checked_in">Checked In</option><option value="completed">Completed</option><option value="no_show">No Show</option><option value="cancelled">Cancelled</option><option value="last_minute_cancelled">Last-Minute Cancelled</option><option value="waitlisted">Waitlisted</option></select><Button variant="secondary">Search</Button></Form></PageCard><section className="mt-6" aria-label="Appointments">{loaderData.appointments.length ? <div className="space-y-4">{loaderData.appointments.map((appointment) => <AdminAppointmentCard key={appointment.id} appointment={appointment}/>)}</div> : <div className="rounded-xl border border-[#dfe1e4] bg-white p-8 text-center shadow-sm"><p className="font-semibold text-[#25272b]">No appointments found.</p><p className="mt-2 text-sm text-[#5f6368]">Try a different customer name, email, Consignor ID, or status.</p></div>}</section></div></PageShell>; }
