import { env } from "cloudflare:workers";
import { data, Form, Link, redirect } from "react-router";
import type { Route } from "./+types/admin.booking-events.detail";
import { requireRole } from "../services/auth.server";
import { ConfirmationForm } from "../components/confirmation-form";
import { Notice, PageCard, PageIntro, PageShell } from "../components/design-system";
import { BookingEventForm, saveEvent } from "./admin.booking-events.new";
const runtime = env as unknown as { AUTH_SECRET?: string; BETTER_AUTH_URL?: string };
export async function loader({request,params}:Route.LoaderArgs) { await requireRole(request,env.trice_auction_db,runtime,"admin"); const id=Number(params.id); const event=await env.trice_auction_db.prepare("SELECT id,name,description,opens_at AS opensAt,closes_at AS closesAt,timezone,active,admin_notes AS adminNotes FROM booking_events WHERE id=?").bind(id).first<any>(); if(!event) throw data("Booking Event not found.",{status:404}); const {results:dates}=await env.trice_auction_db.prepare(`SELECT day.id,day.dropoff_date AS date,day.event_name AS name,day.is_open AS isOpen, COUNT(appointment.id) AS appointmentCount, COALESCE(SUM(type.capacity_points),0) AS usedPoints, COALESCE(day.daily_capacity_override,day.capacity_points) AS capacity FROM booking_event_dropoff_dates link JOIN dropoff_days day ON day.id=link.dropoff_day_id LEFT JOIN appointments appointment ON appointment.appointment_date=day.dropoff_date AND appointment.status='scheduled' LEFT JOIN dropoff_types type ON type.id=appointment.dropoff_type_id WHERE link.booking_event_id=? GROUP BY day.id ORDER BY day.dropoff_date`).bind(id).all<any>(); return {event:{...event,active:event.active===1},dates}; }
export async function action({request,params}:Route.ActionArgs) { await requireRole(request,env.trice_auction_db,runtime,"admin"); const id=Number(params.id), form=await request.formData(), intent=String(form.get("intent")||"save"); if(intent==="save"){const result=await saveEvent(form);if(!result.ok)return data(result,{status:400});await env.trice_auction_db.prepare("UPDATE booking_events SET name=?,description=?,opens_at=?,closes_at=?,timezone=?,active=?,admin_notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(result.value.name,result.value.description,result.value.opensAt,result.value.closesAt,result.value.timezone,result.value.active,result.value.adminNotes,id).run();return data({ok:true,message:"Booking Event updated."});} if(intent==="delete"){const count=await env.trice_auction_db.prepare(`SELECT COUNT(*) AS count FROM appointments appointment JOIN dropoff_days day ON day.dropoff_date=appointment.appointment_date JOIN booking_event_dropoff_dates link ON link.dropoff_day_id=day.id WHERE link.booking_event_id=?`).bind(id).first<{count:number}>();if((count?.count??0)>0)return data({ok:false,errors:["This Booking Event has appointments. Deactivate it instead to preserve history."]},{status:400});await env.trice_auction_db.batch([env.trice_auction_db.prepare("DELETE FROM dropoff_day_area_overrides WHERE dropoff_day_id IN (SELECT dropoff_day_id FROM booking_event_dropoff_dates WHERE booking_event_id=?)").bind(id),env.trice_auction_db.prepare("DELETE FROM dropoff_days WHERE id IN (SELECT dropoff_day_id FROM booking_event_dropoff_dates WHERE booking_event_id=?)").bind(id),env.trice_auction_db.prepare("DELETE FROM booking_events WHERE id=?").bind(id)]);return redirect("/admin/booking-events");}return data({ok:false,errors:["Unknown action."]},{status:400}); }
export default function BookingEventDetail({loaderData,actionData}:Route.ComponentProps){const {event,dates}=loaderData;return <PageShell><div className="max-w-5xl"><Link to="/admin/booking-events" className="font-bold text-[#9d302f] underline">← Booking Events</Link><PageIntro eyebrow="Trice Auctions · Administration" title={event.name}>Manage this public signup event and its Drop-Off Dates.</PageIntro>{actionData && "message" in actionData?<Notice variant="success">{actionData.message}</Notice>:null}{actionData && "errors" in actionData?<Notice variant="error">{actionData.errors.join(" ")}</Notice>:null}<BookingEventForm event={event} submitLabel="Save Booking Event"/><section className="mt-8"><div className="flex items-center justify-between"><h2 className="text-2xl font-bold">Drop-Off Dates</h2><Link to={`/admin/schedule/new?bookingEventId=${event.id}`} className="ta-button ta-button-primary">+ Add Drop-Off Date</Link></div><div className="mt-4 space-y-3">{dates.map(date=><PageCard key={date.id} title={date.name||date.date}><p>{date.date} · {date.isOpen?"Open":"Closed"} · {date.appointmentCount} appointments</p><p className="mt-1 text-sm text-[#5f6368]">Capacity: {date.usedPoints} / {date.capacity} used</p><Link to={`/admin/schedule/${date.id}`} className="mt-3 inline-flex font-bold text-[#9d302f] underline">View / edit Drop-Off Date</Link></PageCard>)}{!dates.length?<PageCard title="No Drop-Off Dates"><p>Add one or more dates for customers to choose from after this event opens.</p></PageCard>:null}</div></section><section className="mt-8 rounded-xl border border-red-200 bg-red-50 p-5"><h2 className="font-bold">Delete Booking Event</h2><p className="mt-1 text-sm">Unused Booking Events and their unused Drop-Off Dates can be permanently deleted. Events with appointments must be deactivated instead.</p><ConfirmationForm method="post" className="mt-3" confirmation={{title:"Delete Booking Event?",description:"This permanently deletes the Booking Event and its unused Drop-Off Dates.",confirmLabel:"Permanently delete",destructive:true}}><input type="hidden" name="intent" value="delete"/><button className="font-semibold text-red-800 underline">Delete Booking Event</button></ConfirmationForm></section></div></PageShell>;}
