import { env } from "cloudflare:workers";
import { data, Form, Link, redirect } from "react-router";
import type { Route } from "./+types/admin.booking-events.new";
import { requireRole } from "../services/auth.server";
import { Notice, PageIntro, PageShell } from "../components/design-system";
import { bookingEventInputValue, OPERATIONAL_TIMEZONE, zonedDateTimeToUtc } from "../lib/booking-event-time";
const runtime = env as unknown as { AUTH_SECRET?: string; BETTER_AUTH_URL?: string };
export async function action({ request }: Route.ActionArgs) { await requireRole(request, env.trice_auction_db, runtime, "admin"); const form = await request.formData(); const result = await saveEvent(form); if (!result.ok) return data(result, {status:400}); const event = await env.trice_auction_db.prepare("INSERT INTO booking_events (name, description, opens_at, closes_at, timezone, active, admin_notes, timestamp_storage_version) VALUES (?, ?, ?, ?, ?, ?, ?, 2) RETURNING id").bind(result.value.name, result.value.description, result.value.opensAt, result.value.closesAt, result.value.timezone, result.value.active, result.value.adminNotes).first<{id:number}>(); return redirect(`/admin/booking-events/${event!.id}`); }
export default function NewBookingEvent({ actionData }: Route.ComponentProps) { return <PageShell><div className="max-w-3xl"><Link to="/admin/booking-events" className="font-bold text-[#9d302f] underline">← Booking Events</Link><PageIntro eyebrow="Trice Auctions · Administration" title="New Booking Event">Save the customer-facing signup window first, then add Drop-Off Dates with their own capacities.</PageIntro>{actionData && !actionData.ok ? <Notice variant="error">{actionData.errors.join(" ")}</Notice> : null}<BookingEventForm /></div></PageShell>; }
export function BookingEventForm({ event, submitLabel = "Create Booking Event" }: { event?: {name:string;description:string|null;opensAt:string;closesAt:string|null;timezone:string;active:boolean;adminNotes:string|null;timeStorageVersion?:number}; submitLabel?:string }) { const timezone = event?.timezone ?? OPERATIONAL_TIMEZONE; return <Form method="post" className="grid gap-5 rounded-xl border border-[#dfe1e4] bg-white p-6"><label className="ta-field">Name / title<input required name="name" defaultValue={event?.name ?? ""}/></label><label className="ta-field">Description <span className="font-normal">(optional, customer-facing)</span><textarea name="description" defaultValue={event?.description ?? ""} className="min-h-28"/></label><div className="grid gap-5 sm:grid-cols-2"><label className="ta-field">Signup opens<input required name="opensAt" type="datetime-local" defaultValue={bookingEventInputValue(event?.opensAt, timezone, event?.timeStorageVersion)}/></label><label className="ta-field">Signup closes <span className="font-normal">(optional)</span><input name="closesAt" type="datetime-local" defaultValue={bookingEventInputValue(event?.closesAt, timezone, event?.timeStorageVersion)}/></label></div><label className="ta-field">Timezone<input required name="timezone" defaultValue={timezone}/></label><label className="ta-field">Internal admin notes <span className="font-normal">(optional)</span><textarea name="adminNotes" defaultValue={event?.adminNotes ?? ""}/></label><label className="font-semibold"><input className="mr-2" name="active" type="checkbox" defaultChecked={event?.active ?? true}/>Active for public signup</label><button className="ta-button ta-button-primary">{submitLabel}</button></Form>; }
export async function saveEvent(form: FormData) { const name=String(form.get("name")||"").trim(), opens=String(form.get("opensAt")||""), closes=String(form.get("closesAt")||""), timezone=String(form.get("timezone")||OPERATIONAL_TIMEZONE).trim(); const errors:string[]=[]; if(!name) errors.push("Name is required."); const opensInstant=zonedDateTimeToUtc(opens, timezone), closesInstant=closes ? zonedDateTimeToUtc(closes, timezone) : null; if(!opensInstant) errors.push("A valid signup opening date and time is required."); if(closes && !closesInstant) errors.push("The closing date and time is invalid."); const opensAt=opensInstant?.toISOString() ?? "", closesAt=closesInstant?.toISOString() ?? null; if(opensAt && closesAt && closesAt <= opensAt) errors.push("Signup closing must be after signup opening."); if(timezone !== OPERATIONAL_TIMEZONE) errors.push(`Timezone must be ${OPERATIONAL_TIMEZONE}.`); return errors.length ? {ok:false as const,errors} : {ok:true as const,value:{name,description:String(form.get("description")||"").trim()||null,opensAt,closesAt,timezone,active:form.has("active")?1:0,adminNotes:String(form.get("adminNotes")||"").trim()||null}}; }
