import { env } from "cloudflare:workers";
import { data, Form } from "react-router";
import type { Route } from "./+types/admin.notifications";
import { requireRole } from "../services/auth.server";
import { getNotificationSettings, saveNotificationSettings } from "../services/notification.server";
import { PageIntro, PageShell, Notice } from "../components/design-system";
const runtime = env as unknown as { AUTH_SECRET?: string; BETTER_AUTH_URL?: string };
export async function loader({request}:Route.LoaderArgs){await requireRole(request,env.trice_auction_db,runtime,"admin");return {settings:await getNotificationSettings(env.trice_auction_db)};}
export async function action({request}:Route.ActionArgs){await requireRole(request,env.trice_auction_db,runtime,"admin");const f=await request.formData();const minutes=(name:string)=>Math.max(0,Math.floor(Number(f.get(name))||0));await saveNotificationSettings(env.trice_auction_db,{"notifications.first_reminder_enabled":f.get("firstEnabled")==="on"?"1":"0","notifications.first_reminder_offset_minutes":String(minutes("firstOffset")),"notifications.second_reminder_enabled":f.get("secondEnabled")==="on"?"1":"0","notifications.second_reminder_offset_minutes":String(minutes("secondOffset")),"notifications.email_enabled":f.get("emailEnabled")==="on"?"1":"0","notifications.sms_enabled":f.get("smsEnabled")==="on"?"1":"0"});return data({ok:true});}
export default function AdminNotifications({loaderData,actionData}:Route.ComponentProps){const s=loaderData.settings;return <PageShell><div className="max-w-3xl"><PageIntro eyebrow="Trice Auctions · Administration" title="Notifications">Configure transactional appointment channels and reminder timing. Provider credentials are Worker secrets and are never shown here.</PageIntro>{actionData?.ok?<Notice variant="success">Notification settings saved.</Notice>:null}<Form method="post" className="mt-6 space-y-6 rounded-xl border bg-white p-6"><fieldset><legend className="text-xl font-bold">Customer reminders</legend><Reminder name="first" label="First reminder" enabled={s["notifications.first_reminder_enabled"]==="1"} offset={s["notifications.first_reminder_offset_minutes"]}/><Reminder name="second" label="Second reminder" enabled={s["notifications.second_reminder_enabled"]==="1"} offset={s["notifications.second_reminder_offset_minutes"]}/><p className="mt-3 text-sm text-stone-600">Offsets are minutes before the appointment (7 days = 10080, 48 hours = 2880, day before = 1440).</p></fieldset><fieldset className="border-t pt-6"><legend className="text-xl font-bold">Channels</legend><label className="mt-4 flex gap-3"><input name="emailEnabled" type="checkbox" defaultChecked={s["notifications.email_enabled"]==="1"}/><span>Email globally enabled</span></label><label className="mt-3 flex gap-3"><input name="smsEnabled" type="checkbox" defaultChecked={s["notifications.sms_enabled"]==="1"}/><span>SMS globally enabled</span></label></fieldset><button className="ta-button ta-button-primary">Save notification settings</button></Form></div></PageShell>}
function Reminder({name,label,enabled,offset}:{name:"first"|"second";label:string;enabled:boolean;offset:string}){return <div className="mt-5 grid gap-3 sm:grid-cols-[1fr_12rem]"><label className="flex gap-3"><input name={`${name}Enabled`} type="checkbox" defaultChecked={enabled}/><span>{label} enabled</span></label><label className="text-sm font-semibold">Minutes before appointment<input name={`${name}Offset`} type="number" min="0" defaultValue={offset} className="mt-1 block w-full rounded border p-2 font-normal"/></label></div>}
