import { env } from "cloudflare:workers";
import { data, Form } from "react-router";
import type { Route } from "./+types/admin.booking-releases";
import { requireRole } from "../services/auth.server";
import { PageCard, PageIntro, PageShell, Button } from "../components/design-system";
const runtime=env as unknown as {AUTH_SECRET?:string;BETTER_AUTH_URL?:string};
export async function loader({request}:Route.LoaderArgs){await requireRole(request,env.trice_auction_db,runtime,"admin");const [releases,events]=await Promise.all([env.trice_auction_db.prepare("SELECT id,name,opens_at AS opensAt,closes_at AS closesAt,timezone,active,admin_notes AS adminNotes FROM booking_releases ORDER BY opens_at DESC").all<any>(),env.trice_auction_db.prepare("SELECT id,dropoff_date AS date,event_name AS name FROM dropoff_days ORDER BY dropoff_date").all<any>()]);return {releases:releases.results,events:events.results};}
export async function action({request}:Route.ActionArgs){await requireRole(request,env.trice_auction_db,runtime,"admin");const f=await request.formData();const name=String(f.get("name")||"").trim(),opens=String(f.get("opensAt")||"");if(!name||!opens)return data({error:"Name and opening time are required."},{status:400});const eventIds=Array.from(f.getAll("eventId")).map(Number).filter(Number.isInteger);const release=await env.trice_auction_db.prepare("INSERT INTO booking_releases (name,opens_at,closes_at,timezone,active,admin_notes) VALUES (?, ?, ?, ?, ?, ?) RETURNING id").bind(name,new Date(opens).toISOString(),f.get("closesAt")?new Date(String(f.get("closesAt"))).toISOString():null,String(f.get("timezone")||"America/New_York"),f.has("active")?1:0,String(f.get("adminNotes")||"")||null).first<{id:number}>();if(release&&eventIds.length)await env.trice_auction_db.batch(eventIds.map(id=>env.trice_auction_db.prepare("INSERT INTO booking_release_events (booking_release_id,dropoff_day_id) VALUES (?,?)").bind(release.id,id)));return data({message:"Booking release created."});}
export default function Releases({loaderData,actionData}:Route.ComponentProps){return <PageShell><div className="max-w-5xl"><PageIntro eyebrow="Trice Auctions · Administration" title="Booking Releases">Control when saved Drop-Off Events open for signup.</PageIntro>{actionData&&"message" in actionData?<p role="status">{actionData.message}</p>:null}<PageCard title="Create Booking Release"><Form method="post" className="grid gap-4 sm:grid-cols-2"><label className="ta-field">Name<input name="name" required/></label><label className="ta-field">Signup opens<input name="opensAt" type="datetime-local" required/></label><label className="ta-field">Signup closes (optional)<input name="closesAt" type="datetime-local"/></label><label className="ta-field">Timezone<input name="timezone" defaultValue="America/New_York" required/></label><label className="ta-field sm:col-span-2">Admin notes<textarea name="adminNotes"/></label><label><input name="active" type="checkbox" defaultChecked/> Active</label><fieldset className="sm:col-span-2"><legend className="font-semibold">Available Drop-Off Events</legend>{loaderData.events.map(e=><label key={e.id} className="mr-4 inline-block"><input type="checkbox" name="eventId" value={e.id}/> {e.date}{e.name?` — ${e.name}`:""}</label>)}</fieldset><Button className="sm:col-span-2">Create release</Button></Form></PageCard><section className="mt-6 space-y-4">{loaderData.releases.map(r=><PageCard key={r.id} title={r.name}><p>Opens: {r.opensAt} · {r.active?"Active":"Inactive"}</p><p>{r.closesAt?`Closes: ${r.closesAt}`:"No closing time"}</p></PageCard>)}</section></div></PageShell>}
