import { env } from "cloudflare:workers";
import { data, Form, Link } from "react-router";
import type { Route } from "./+types/employee.detail";
import { ConfirmationForm } from "../components/confirmation-form";
import { requireAnyRole } from "../services/auth.server";
import { addCustomerPrivateNote, getCustomerAppointmentHistory, getCustomerPrivateNotes, getCustomerStanding, removeCustomerDropoffBan, setCustomerDropoffBan } from "../services/customer-standing.server";

const runtime = env as unknown as { AUTH_SECRET?: string; BETTER_AUTH_URL?: string };
const STAFF_ROLES: ("employee" | "manager" | "admin")[] = ["employee", "manager", "admin"];

export async function loader({ request, params }: Route.LoaderArgs) {
  await requireAnyRole(request, env.trice_auction_db, runtime, STAFF_ROLES);
  const appointment = await env.trice_auction_db.prepare(`SELECT a.id, a.user_id AS customerUserId, a.appointment_date AS appointmentDate, a.description, a.admin_notes AS adminNotes, a.status, u.first_name AS firstName, u.last_name AS lastName, u.email AS customerEmail, d.name AS loadType FROM appointments a JOIN users u ON u.id = a.user_id JOIN dropoff_types d ON d.id = a.dropoff_type_id WHERE a.id = ?`).bind(Number(params.id)).first<any>();
  if (!appointment) throw new Response("Not Found", { status: 404 });
  const [standing, privateNotes, appointmentHistory] = await Promise.all([getCustomerStanding(env.trice_auction_db, appointment.customerUserId), getCustomerPrivateNotes(env.trice_auction_db, appointment.customerUserId), getCustomerAppointmentHistory(env.trice_auction_db, appointment.customerUserId)]);
  return { appointment, standing, privateNotes, appointmentHistory };
}

export async function action({ request, params }: Route.ActionArgs) {
  const actor = await requireAnyRole(request, env.trice_auction_db, runtime, STAFF_ROLES);
  const appointment = await env.trice_auction_db.prepare("SELECT user_id AS customerUserId FROM appointments WHERE id = ?").bind(Number(params.id)).first<{ customerUserId: number }>();
  if (!appointment) throw new Response("Not Found", { status: 404 });
  const form = await request.formData(); const intent = String(form.get("intent") || "save-operational");
  if (intent === "add-private-note") { const result = await addCustomerPrivateNote(env.trice_auction_db, { customerUserId: appointment.customerUserId, actor, noteText: String(form.get("noteText") || "") }); return data(result, { status: result.ok ? 200 : 400 }); }
  if (intent === "ban-customer") { const result = await setCustomerDropoffBan(env.trice_auction_db, { customerUserId: appointment.customerUserId, actor, reason: String(form.get("banReason") || "") }); return data(result, { status: result.ok ? 200 : 400 }); }
  if (intent === "unban-customer") { const result = await removeCustomerDropoffBan(env.trice_auction_db, appointment.customerUserId); return data(result, { status: result.ok ? 200 : 400 }); }
  if (intent !== "save-operational") return data({ ok: false, errors: ["Invalid action."] }, { status: 400 });
  const status = String(form.get("status"));
  if (!["scheduled", "checked_in", "completed", "no_show"].includes(status)) return data({ ok: false, errors: ["Invalid status."] }, { status: 400 });
  await env.trice_auction_db.prepare("UPDATE appointments SET admin_notes = ?, status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?").bind(String(form.get("adminNotes") || ""), status, Number(params.id)).run();
  return data({ ok: true, message: status === "no_show" ? "Appointment marked No Show. You may separately ban the customer if appropriate." : "Operational update saved." });
}

export default function Detail({ loaderData, actionData }: Route.ComponentProps) {
  const { appointment: a, standing, privateNotes, appointmentHistory } = loaderData;
  const success = actionData && "message" in actionData ? actionData.message : null;
  const errors = actionData && "errors" in actionData ? actionData.errors ?? [] : [];
  const customerName = `${a.firstName} ${a.lastName}`.trim() || a.customerEmail;
  return <main className="min-h-screen bg-stone-50 text-stone-900"><div className="mx-auto max-w-3xl px-6 py-12 sm:py-16"><Link to="/employee" className="text-sm font-semibold text-amber-800">← Today’s drop-offs</Link><header className="mt-5 border-b border-stone-200 pb-7"><p className="text-sm font-semibold tracking-[0.18em] text-amber-700 uppercase">Appointment detail</p><h1 className="mt-2 text-3xl font-bold">{customerName}</h1><p className="mt-2 text-stone-700">{a.appointmentDate} · {a.loadType}</p>{a.description ? <p className="mt-3 text-stone-600">{a.description}</p> : null}</header>{success ? <Notice variant="success">{success}</Notice> : null}{errors.length ? <Notice variant="error">{errors.join(" ")}</Notice> : null}
    <section className="mt-6 rounded-2xl border border-stone-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Customer standing</h2><p className="mt-2 font-semibold">Drop-Off Status: <span className={standing?.dropoffBanned ? "text-red-700" : "text-emerald-700"}>{standing?.dropoffBanned ? "Banned" : "Eligible"}</span></p>{standing?.dropoffBanned ? <p className="mt-2 text-sm text-stone-700">Reason: {standing.banReason || "No reason recorded."}{standing.bannedAt ? ` · Recorded ${standing.bannedAt}` : ""}{standing.bannedByName ? ` by ${standing.bannedByName}` : ""}</p> : <p className="mt-2 text-sm text-stone-600">This customer may schedule drop-offs.</p>}{standing?.dropoffBanned ? <ConfirmationForm method="post" className="mt-4" confirmation={{ title: "Allow customer to schedule again?", description: "This removes the customer’s drop-off ban.", confirmLabel: "Unban customer", destructive: true }}><input type="hidden" name="intent" value="unban-customer"/><button className="rounded-lg border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700">Remove drop-off ban</button></ConfirmationForm> : <ConfirmationForm method="post" className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]" confirmation={{ title: "Ban customer from drop-offs?", description: "They can still sign in and view their account, but cannot schedule new drop-offs.", confirmLabel: "Ban customer", destructive: true }}><input type="hidden" name="intent" value="ban-customer"/><label className="text-sm font-semibold">Ban reason<input required name="banReason" className="mt-1 block w-full rounded-lg border border-stone-300 p-2 font-normal"/></label><button className="self-end rounded-lg bg-red-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-red-800">Ban customer</button></ConfirmationForm>}</section>
    <section className="mt-6 rounded-2xl border border-stone-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Operational update</h2><Form method="post" className="mt-4 space-y-3"><input type="hidden" name="intent" value="save-operational"/><label className="block text-sm font-semibold">Internal operational notes<textarea name="adminNotes" defaultValue={a.adminNotes || ""} className="mt-2 block min-h-28 w-full rounded-lg border border-stone-300 p-3 font-normal"/></label><label className="block text-sm font-semibold">Appointment status<select name="status" defaultValue={a.status} className="mt-2 block w-full rounded-lg border border-stone-300 bg-white p-2 font-normal"><option value="scheduled">Scheduled</option><option value="checked_in">Checked in</option><option value="completed">Completed</option><option value="no_show">No Show</option></select></label><p className="text-sm text-stone-600">Marking an appointment No Show does not ban the customer automatically.</p><button className="rounded-lg bg-stone-900 px-4 py-2.5 text-sm font-semibold text-white">Save operational update</button></Form></section>
    <section className="mt-6 rounded-2xl border border-stone-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Internal Notes — Not visible to customer</h2><Form method="post" className="mt-4 flex flex-col gap-3"><input type="hidden" name="intent" value="add-private-note"/><textarea required name="noteText" className="min-h-24 rounded-lg border border-stone-300 p-3" placeholder="Add a private customer note"/><button className="self-start rounded-lg bg-stone-900 px-4 py-2.5 text-sm font-semibold text-white">Add private note</button></Form><NoteHistory notes={privateNotes}/></section>
    <section className="mt-6 rounded-2xl border border-stone-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Appointment history</h2>{appointmentHistory.length ? <ul className="mt-3 divide-y divide-stone-200">{appointmentHistory.map((item) => <li key={item.id} className="py-3 text-sm"><span className="font-semibold">{item.appointmentDate}</span> · {item.loadType} · <span className="capitalize">{item.status.replace("_", " ")}</span></li>)}</ul> : <p className="mt-3 text-sm text-stone-600">No appointment history.</p>}</section>
  </div></main>;
}

function NoteHistory({ notes }: { notes: { id: number; noteText: string; createdAt: string; authorName: string }[] }) { return notes.length ? <ol className="mt-5 divide-y divide-stone-200">{notes.map((note) => <li key={note.id} className="py-3"><p className="whitespace-pre-wrap text-sm">{note.noteText}</p><p className="mt-1 text-xs text-stone-500">{note.authorName} · {note.createdAt}</p></li>)}</ol> : <p className="mt-5 text-sm text-stone-600">No private notes have been added.</p>; }
function Notice({ variant, children }: { variant: "success" | "error"; children: React.ReactNode }) { return <p className={variant === "success" ? "mt-6 rounded border border-emerald-200 bg-emerald-50 p-4 text-emerald-950" : "mt-6 rounded border border-red-200 bg-red-50 p-4 text-red-950"} role={variant === "success" ? "status" : "alert"}>{children}</p>; }
