import { env } from "cloudflare:workers";
import { data, Form, redirect } from "react-router";
import type { Route } from "./+types/login";
import { getAuth, syncApplicationUser } from "../services/auth.server";
import { getPendingBookingToken } from "../services/pending-booking.server";
import { allowSensitiveUnauthenticatedAttempt } from "../services/public-form-protection.server";
const runtime = env as unknown as { AUTH_SECRET?: string; BETTER_AUTH_URL?: string };
export async function action({ request }: Route.ActionArgs) { const form = await request.formData(); if (!String(form.get("email") ?? "").trim() || !String(form.get("password") ?? "")) return data({ error: "Invalid email or password." }, { status: 401 }); if (!await allowSensitiveUnauthenticatedAttempt(env.trice_auction_db, request, "login")) return data({ error: "We couldn’t verify this submission. Please try again." }, { status: 429 }); const response = await getAuth(env.trice_auction_db, runtime).handler(new Request(new URL("/api/auth/sign-in/email", request.url), { method: "POST", headers: { "content-type": "application/json", origin: new URL(request.url).origin }, body: JSON.stringify({ email: String(form.get("email") ?? "").trim().toLowerCase(), password: String(form.get("password") ?? "") }) })); if (!response.ok) return data({ error: "Invalid email or password." }, { status: 401 }); const payload = await response.json() as { user: { id: string; email: string; name?: string } }; await syncApplicationUser(env.trice_auction_db, payload.user); const applicationUser = await env.trice_auction_db.prepare("SELECT must_change_password AS mustChangePassword FROM users WHERE auth_user_id = ?").bind(payload.user.id).first<{ mustChangePassword: number }>(); return redirect(applicationUser?.mustChangePassword ? "/change-password" : (getPendingBookingToken(request) ? "/?resume=1" : "/"), { headers: response.headers }); }
export default function Login({ actionData }: Route.ComponentProps) { return <main className="mx-auto max-w-md p-8"><h1 className="text-3xl font-bold">Log in</h1>{actionData?.error && <p role="alert">{actionData.error}</p>}<Form method="post" className="mt-6 space-y-4"><input required type="email" name="email" placeholder="Email" className="w-full border p-2"/><input required type="password" name="password" placeholder="Password" className="w-full border p-2"/><button className="bg-stone-900 px-4 py-2 text-white">Log in</button></Form></main>; }
