import { env } from "cloudflare:workers";
import { data, Form, Link } from "react-router";
import type { Route } from "./+types/my-appointments.detail";
import { requireOwnership, requireUser } from "../services/auth.server";
import { createBooking, getBookingOptions } from "../services/booking.server";
const runtime=env as unknown as {AUTH_SECRET?:string;BETTER_AUTH_URL?:string};
export async function loader({request,params}:Route.LoaderArgs){const u=await requireUser(request,env.trice_auction_db,runtime);const a=await env.trice_auction_db.prepare("SELECT id,user_id AS userId,appointment_date AS appointmentDate,appointment_time AS appointmentTime,dropoff_type_id AS dropoffTypeId,description,status FROM appointments WHERE id=?").bind(Number(params.id)).first<any>();if(!a)throw new Response("Not Found",{status:404});requireOwnership(u,a.userId);const allocations=(await env.trice_auction_db.prepare("SELECT item_area_id AS itemAreaId,allocation_percent AS percentage FROM appointment_area_allocations WHERE appointment_id=?").bind(a.id).all<any>()).results;return {a,allocations,options:await getBookingOptions(env.trice_auction_db)}}
export async function action({request,params}:Route.ActionArgs){const u=await requireUser(request,env.trice_auction_db,runtime);const a=await env.trice_auction_db.prepare("SELECT user_id AS userId,status FROM appointments WHERE id=?").bind(Number(params.id)).first<any>();if(!a)throw new Response("Not Found",{status:404});requireOwnership(u,a.userId);const f=await request.formData();const allocations=Array.from(f.entries()).filter(([k])=>k.startsWith("allocation-")).map(([k,v])=>({itemAreaId:Number(k.slice(11)),percentage:Number(v)}));return data(await createBooking(env.trice_auction_db,{appointmentId:Number(params.id),userId:u.id,appointmentDate:String(f.get("appointmentDate")),appointmentTime:String(f.get("appointmentTime")||""),dropoffTypeId:Number(f.get("dropoffTypeId")),description:String(f.get("description")||""),allocations}))}
export default function Detail({loaderData}:Route.ComponentProps){return <main className="mx-auto max-w-2xl p-8"><Link to="/my-appointments">← My Appointments</Link><h1 className="mt-4 text-3xl font-bold">Edit appointment</h1><Form method="post" className="space-y-3"><input type="date" name="appointmentDate" defaultValue={loaderData.a.appointmentDate}/><input type="time" name="appointmentTime" defaultValue={loaderData.a.appointmentTime??""}/><select name="dropoffTypeId" defaultValue={loaderData.a.dropoffTypeId}>{loaderData.options.dropoffTypes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>{loaderData.options.itemAreas.map(x=><label key={x.id}>{x.name}<input name={`allocation-${x.id}`} type="number" defaultValue={loaderData.allocations.find((a:any)=>a.itemAreaId===x.id)?.percentage??0}/>%</label>)}<textarea name="description" defaultValue={loaderData.a.description??""}/><button>Save changes</button></Form></main>}
