import { env } from "cloudflare:workers";
import { data, Form, Link } from "react-router";
import type { Route } from "./+types/my-appointments";
import { requireOwnership, requireUser } from "../services/auth.server";
import { clearBookingSuccessFlashCookie, consumeBookingSuccessFlash, getBookingSuccessFlashToken } from "../services/booking-success-flash.server";
import { ConfirmationForm } from "../components/confirmation-form";
import { Button, Notice, PageCard, PageIntro, PageShell } from "../components/design-system";
import { cancelScheduledAppointment } from "../services/notification.server";
const runtime = env as unknown as { AUTH_SECRET?: string; BETTER_AUTH_URL?: string };
export async function loader({ request }: Route.LoaderArgs) { const user = await requireUser(request, env.trice_auction_db, runtime); const token = getBookingSuccessFlashToken(request); const [appointmentResult, bookingSuccess] = await Promise.all([env.trice_auction_db.prepare(`SELECT a.id, a.appointment_date AS appointmentDate, a.status, d.name AS loadType, day.event_name AS eventName, day.visibility FROM appointments a JOIN dropoff_types d ON d.id=a.dropoff_type_id LEFT JOIN dropoff_days day ON day.dropoff_date=a.appointment_date WHERE a.user_id=? ORDER BY a.appointment_date DESC, a.id DESC`).bind(user.id).all<{id:number;appointmentDate:string;status:string;loadType:string;eventName:string|null;visibility:"public"|"private"|null}>(), consumeBookingSuccessFlash(env.trice_auction_db, user.id, token)]); return data({ appointments: appointmentResult.results, bookingSuccess }, token ? { headers: { "Set-Cookie": clearBookingSuccessFlashCookie(request) } } : undefined); }
export async function action({ request }: Route.ActionArgs) { const user = await requireUser(request, env.trice_auction_db, runtime); const form=await request.formData(); const id=Number(form.get("appointmentId")); const appointment=await env.trice_auction_db.prepare("SELECT user_id AS userId, status FROM appointments WHERE id=?").bind(id).first<{userId:number;status:string}>(); if(!appointment) return data({error:"Appointment not found."},{status:404}); requireOwnership(user,appointment.userId); if(appointment.status!=="scheduled") return data({error:"Only scheduled appointments can be cancelled."},{status:400}); const result=await cancelScheduledAppointment(env.trice_auction_db,id,env as never,user.email); return result.cancelled ? data({message:"Appointment cancelled."}) : data({error:"Only scheduled appointments can be cancelled."},{status:400}); }
export default function MyAppointments({loaderData,actionData}:Route.ComponentProps){return <PageShell><div className="max-w-4xl"><PageIntro eyebrow="Customer portal" title="My Appointments">Review, update, or cancel your scheduled consignment drop-offs.</PageIntro>{loaderData.bookingSuccess&&<Notice variant="success"><p className="font-semibold">Your drop-off appointment was created.</p><p className="mt-1">{loaderData.bookingSuccess.appointmentDate} · {loaderData.bookingSuccess.loadType}</p></Notice>}{actionData && "message" in actionData&&<Notice variant="success">{actionData.message}</Notice>}{actionData && "error" in actionData&&<Notice variant="error">{actionData.error}</Notice>}<div className="space-y-5">{loaderData.appointments.map(a=><PageCard key={a.id} title={`${a.eventName || a.appointmentDate} · ${a.loadType}`}><div className="flex flex-wrap items-center justify-between gap-4"><p className="font-medium capitalize text-[#555960]">{a.appointmentDate} · {a.status}{a.visibility === "private" ? " · Private appointment" : ""}</p><div className="flex flex-wrap gap-3"><Link className="ta-button ta-button-secondary" to={`/my-appointments/${a.id}`}>{a.visibility === "private" ? "View" : "View / edit"}</Link>{a.status==="scheduled"&&<ConfirmationForm confirmation={{title:"Cancel drop-off appointment?",description:<><p>Are you sure you want to cancel this drop-off appointment?</p><p className="mt-2 text-sm">{a.appointmentDate} · {a.loadType}</p></>,confirmLabel:"Cancel appointment",destructive:true}} method="post"><input type="hidden" name="appointmentId" value={a.id}/><Button variant="destructive">Cancel</Button></ConfirmationForm>}</div></div></PageCard>)}{!loaderData.appointments.length&&<PageCard title="No appointments yet"><p>When you are ready, <Link className="font-bold text-[#9d302f] underline" to="/">schedule a drop-off</Link>.</p></PageCard>}</div></div></PageShell>}
