import { env } from "cloudflare:workers";
import { data, Form, Link } from "react-router";
import type { Route } from "./+types/my-appointments";
import { requireOwnership, requireUser } from "../services/auth.server";
import { clearBookingSuccessFlashCookie, consumeBookingSuccessFlash, getBookingSuccessFlashToken } from "../services/booking-success-flash.server";
const runtime = env as unknown as { AUTH_SECRET?: string; BETTER_AUTH_URL?: string };
export async function loader({ request }: Route.LoaderArgs) { const user = await requireUser(request, env.trice_auction_db, runtime); const token = getBookingSuccessFlashToken(request); const [appointmentResult, bookingSuccess] = await Promise.all([env.trice_auction_db.prepare(`SELECT a.id, a.appointment_date AS appointmentDate, a.status, d.name AS loadType FROM appointments a JOIN dropoff_types d ON d.id=a.dropoff_type_id WHERE a.user_id=? ORDER BY a.appointment_date DESC`).bind(user.id).all<{id:number;appointmentDate:string;status:string;loadType:string}>(), consumeBookingSuccessFlash(env.trice_auction_db, user.id, token)]); return data({ appointments: appointmentResult.results, bookingSuccess }, token ? { headers: { "Set-Cookie": clearBookingSuccessFlashCookie(request) } } : undefined); }
export async function action({ request }: Route.ActionArgs) { const user = await requireUser(request, env.trice_auction_db, runtime); const form=await request.formData(); const id=Number(form.get("appointmentId")); const appointment=await env.trice_auction_db.prepare("SELECT user_id AS userId, status FROM appointments WHERE id=?").bind(id).first<{userId:number;status:string}>(); if(!appointment) return data({error:"Appointment not found."},{status:404}); requireOwnership(user,appointment.userId); if(appointment.status!=="scheduled") return data({error:"Only scheduled appointments can be cancelled."},{status:400}); await env.trice_auction_db.prepare("UPDATE appointments SET status='cancelled', updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(id).run(); return data({message:"Appointment cancelled."}); }
export default function MyAppointments({loaderData,actionData}:Route.ComponentProps){return <main className="mx-auto max-w-3xl p-8"><h1 className="text-3xl font-bold">My Appointments</h1>{loaderData.bookingSuccess&&<section className="mt-4 rounded border border-emerald-200 bg-emerald-50 p-4 text-emerald-950" role="status"><p className="font-semibold">Your drop-off appointment was created.</p><p className="mt-1">{loaderData.bookingSuccess.appointmentDate} · {loaderData.bookingSuccess.appointmentTime||"Time TBD"} · {loaderData.bookingSuccess.loadType}</p></section>}{actionData && "message" in actionData&&<p role="status">{actionData.message}</p>}{actionData && "error" in actionData&&<p role="alert">{actionData.error}</p>}<div className="mt-6 space-y-3">{loaderData.appointments.map(a=><article key={a.id} className="border p-4"><Link to={`/my-appointments/${a.id}`}><b>{a.appointmentDate}</b></Link><p>{a.loadType} · {a.status}</p>{a.status==="scheduled"&&<><Link to={`/my-appointments/${a.id}`}>View / edit</Link><Form method="post"><input type="hidden" name="appointmentId" value={a.id}/><button className="text-red-700">Cancel</button></Form></>}</article>)}{!loaderData.appointments.length&&<p>No appointments yet. <Link to="/">Schedule one</Link>.</p>}</div></main>}
